### ISSUE TITLE
Ability to skip defaultNetworkHTMLRule if tooltip is rendered via defaultNetworkSVGRule

### ISSUE THREAD

**Issue by torioLuz** [emeeks/semiotic#107]
Currently if we set _hoverAnnotation={true}_, both _defaultNetworkSVGRule_ and _defaultNetworkHTMLRule_ will be called for every "frame-hover". If users choose to use _defaultNetworkSVGRule_ to render a custom tooltip content (e.g. using react-annotation), we'd probably don't want _defaultNetworkHTMLRule_ to also construct it's default tooltip content (which currently executes regardless). 

Does the reasoning above make sense? Or do tooltips always have to be handled by  tooltipContent prop (which is in turn handled by _defaultNetworkHTMLRule_ )?

**Comment by emeeks** [comment]
The pattern I use is to write a custom HTML rule that doesn't return anything for `frame-hover`. I realize that's a bit cumbersome, so if you have a suggestion for a clean approach that takes care of it, I'm happy to try to implement it.

**Comment by torioLuz** [comment]
Thanks. I'll follow your pattern for my short term need. 

As for suggestions, what about on tooltipContent users can set a flag to determine whether defaultNetworkSVGRule or defaultNetworkHTMLRule should handle it? If undefined, we can also have it default to defaultNetworkHTMLRule to not break existing usage. Open to any other suggestions of course. 

I've only played around with the NetworkFrame component so far so I can say the change above doesn't seem too bad (effort-wise), and I can help to implement it in NetworkFrame. I haven't familiarized myself with the other frame components so I don't how much effort it'll take to make similar changes there.

**Comment by emeeks** [comment]
I think it's a good idea and makes sense for how people use it. I know the default SVG+HTML tooltip has thrown off some folks so maybe something more sensical for 1.4 should be the plan.

**Comment by emeeks** [comment]
You can specify arrays of annotation rules (as of a release several releases prior) to ensure that you're only running the rules you want.
