### ISSUE TITLE
hoverAnnotation not working?

### ISSUE THREAD

**Issue by epicfaace** [emeeks/semiotic#109]
Here is my code:

```
<ResponsiveORFrame
            title={this.props.title || "Results"}
            size={[300, 300]}
            data={this.props.data}
            oAccessor={oAccessor}
            dynamicColumnWidth={this.props.value || "count"}
            //dynamicColumnWidth={d => sum(d.map(p => p.count))}
            style={d => ({ fill: toMaterialStyle(d[oAccessor]).backgroundColor, stroke: "white" })}
            type={{ type: "bar", innerRadius: 50 }}
            projection="radial"
            margin={{ top: 50, bottom: 50, left: 50, right: 50 }}
            oPadding={1}
            //oLabel={this.getLabel}
            hoverAnnotation={true}
            customClickBehavior={(e) => this.pieceClicked(e)}
            tooltipContent={() => "Hi"}
        />

```

The pie graph displays fine, but when I hover over the pieces, no tooltip is showing up.

**Comment by emeeks** [comment]
Could you post a minimal example on CodePen or CodeSandBox or the equivalent with similar data and functions? When I build a minimal example with those settings it seems to show tooltips just fine:

![untitled](https://user-images.githubusercontent.com/495634/34365188-5d811262-ea42-11e7-924f-5ac2290caea7.gif)

**Comment by epicfaace** [comment]
Thanks. I did some further investigation and it looks like the bootstrap css ([v4.0.0-beta.2](https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css)) was making the tooltips hide. I'll have to investigate this -- do you have any idea what could be interfering from bootstrap to svg's generated by semiotic?

**Comment by emeeks** [comment]
Ah yes, I've seen and heard of that happening. You can wrap your content in its own div with a different className like:
`tooltipContent={d => <div className="no-collision-tooltip"><p>Hi</p></div>}`

I'm afraid there's not much else I can think of, I might namespace all the semiotic stuff in a later release as `semiotic-x` but otherwise I can't think of how to avoid collisions with shared CSS classes.

**Comment by epicfaace** [comment]
Thanks for the insight. However, the solution you suggested isn't working -- perhaps the tooltipContent itself is wrapped in another element that is colliding with bootstrap?

See https://codepen.io/epicfaace/pen/eygygq?editors=1010

**Comment by emeeks** [comment]
Ah, maybe. I'll take a look at your pen.

**Comment by epicfaace** [comment]
Fixed it by adding:
````
.tooltip {
    opacity: 1;
}
````

**Comment by emeeks** [comment]
I was just going to post that:
https://codepen.io/emeeks/pen/gogeOb

I tried everything else, giving inline styles and more specific CSS rules for opacity and none of it worked. How frustrating! Let me know if you see any other issues with bootstrap integration.
