### ISSUE TITLE
Errors on data update

### ISSUE THREAD

**Issue by epicfaace** [emeeks/semiotic#110]
I'm rendering some pie charts with the following code:

```
        <ResponsiveORFrame
            title={this.props.title || "Results"}
            data={this.props.data}
            responsiveWidth={true}
            responsiveHeight={true}
            oAccessor={oAccessor}
            dynamicColumnWidth={this.props.value || "count"}
            style={d => ({ fill: this.getFillColor(d[oAccessor]), stroke: "white" })}
            type={{ type: "bar", innerRadius: 30 }}
            projection="radial"
            margin={{ top: 50, bottom: 50, left: 50, right: 50 }}
            oPadding={1}
            tooltipContent={d => <div><b>{d._id}: </b>{d.count}</div>}
            pieceHoverAnnotation={true}
            customClickBehavior={(e) => this.pieceClicked(e)}
        />
```

Occasionally, when the data updates (i.e., the graphs change from dataset A to dataset B), I'm getting all these errors on the console: (The actual graphs look fine, maybe a bit laggy when they animate).

Is this a big deal? Any idea what could be causing it?

![image](https://user-images.githubusercontent.com/1689183/34392735-14ff49c0-eb1c-11e7-90cd-959a798f2725.png)

**Comment by emeeks** [comment]
I could be that some of the underlying code isn't taking into account when the angle of the arc grows larger than 0.5. I'll take a look.

**Comment by emeeks** [comment]
Could you post an array of the data values before and after for me to reproduce this?
