### ISSUE TITLE
Faceting

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#113]
_Now that Semiotic has matured a bit and most of the bugs are ironed out I'm trying to think of ways to improve the library. Please thumbs up or thumbs down this if you think it would or wouldn't be useful. Also, if you have concerns or ideas, feel free to leave comments._

One of the most useful approaches in data visualization is to build out small multiples. You can do that on your own with Semiotic, but maybe there's room for an integrated feature that allows you to specify how to slice the data, as well as shared resources for interactivity and annotation. In my own work, I've built a few different layers on top Semiotic to allow cross brushing, and it's always a bit of a hassle because you're identifying where X point is on one chart versus the other even though it's the same data.

One thing I really like about this is there's room for innovation in what small multiples means, as right now it's just the same chart several times on a grid but maybe it's different baskets of settings of a Frame so you see all the different network views of your data, or ordinal views, and so on. Likewise, maybe it's dynamic styling or annotations so the variation between the chart isn't about data or filtering but rather how you present and annotate it.

# Implementation Details
* Is it an attribute of a frame or a frame of its own?
* Does it have a shared annotation layer? A shared interaction layer?
* Are minimaps just a specific kind of small multiples?
* Are parallel coordinates just a specific kind of small multiples?

**Comment by curran** [comment]
This would be really cool to have! Vega-lite calls it [facet](https://vega.github.io/vega-lite/docs/facet.html), their implementation/design might be interesting to review.

**Comment by emeeks** [comment]
So I read up a bit about small multiples and looked at other implementations and played through a few different scenarios and noticed a few things and would love to hear what folks think. Below are a few examples of a dataset of Vlad Guerrero's hits and outs, just a simple scatterplot but one where faceting really helps to find patterns and narratives.

* Of course the traditional small multiples need to be supported, which is splitting out data by a dimension. This is like `d3-nest` but for charts and should be as many hierarchical layers as you want.
![screen shot 2018-01-25 at 9 01 42 am](https://user-images.githubusercontent.com/495634/35425713-eca7dc46-0211-11e8-8387-2d800c511bb4.png)

* The resulting matrix itself probably should have some kind of data visualization principles applied. Above is just a naive list, but if this is arranged into a true grid it helps cognition immensely. This implies some kind of columns/rows labeling or even a `GridFrame` that is focused on true grid data.
<img width="1163" alt="screen shot 2018-01-25 at 6 38 32 pm" src="https://user-images.githubusercontent.com/495634/35425709-e53556be-0211-11e8-9f4b-826096292ff0.png">

* Splitting out charts is one thing but small multiples or faceting in effective examples also split out channels. The above not only uses a grid, it splits the data within the chart according to some further degree. Unlike with the matrix, this doesn't seem amenable to multiple levels of hierarchy, it should probably just happen once. But it highlights how `lines` and `areas` in `XYFrame` are more similar to the `oAccessor`-created columns in `ORFrame`.

* `NetworkFrame` is more resilient to displaying more than one level of hierarchy because that's its job.

**Comment by curran** [comment]
Related:

![image](https://user-images.githubusercontent.com/68416/35436766-be6610c4-02b5-11e8-9770-87805f37b2c6.png)

from [Polaris: A System for Query, Analysis and Visualization of Multi-dimensional Relational Databases](https://graphics.stanford.edu/papers/polaris/polaris.pdf) (precursor to Tableau)

**Comment by emeeks** [comment]
Current plan is to implement a `<FacetFrame>` which allows you to pass a set of frames (of different types) or a function that takes a single dataset and returns multiple frames of the same type. The `FacetFrame` would have some shared properties and also a hover annotation of its own to facilitate cross-highlighting among the frames.

**Comment by emeeks** [comment]
https://github.com/emeeks/semiotic/pull/299

**Comment by emeeks** [comment]
FacetController in 1.13.0. Going to close this and leave other faceting/small multiples ideas for separate issues. FacetController is a simple first step toward coordinated extents and tooltips and props, so there's still a lot here to deal with.
