### ISSUE TITLE
Improve Labeling and Annotation

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#114]
_Now that Semiotic has matured a bit and most of the bugs are ironed out I'm trying to think of ways to improve the library. Please thumbs up or thumbs down this if you think it would or wouldn't be useful. Also, if you have concerns or ideas, feel free to leave comments._

One of the things that really sets apart bespoke charts and one-off libraries dedicated to a specific chart (like a Sunburst chart) is their labeling. Weird charts like treemaps have often have their own custom rules to be labeled properly, there's been some cool work done by Noah Veltman on labeling stacked area charts and even bar charts have more options for labeling than you'd think. Add to this the problem of making sure annotations don't collide with labels and it's some serious work.

The benefits of a dedicated attempt to make labeling and annotations work really well aren't just clear labels, there's the possibility that the weird sunburst labeling is actually suitable for a pie chart, or the treemap labels could be used in any rectangular mark. On the other hand, labeling is super difficult, as evidenced by the minor amount of annotation handling options already implemented in Semiotic and their uneven performance.

**Comment by tomshanley** [comment]
labella.js do some nice things too, which may be worth a look.

**Comment by tomshanley** [comment]
I think that this area, in comparison with the other suggestions you have made (maps, chart abstractions and small multiples, is the one most in need of improvement in the D3 space.

**Comment by emeeks** [comment]
I agree @tomshanley, have you got a top ten list of labeling and annotation features you'd like to see or other places where you've seen an awesome labeling feature (besides `labella.js`).

**Comment by tomshanley** [comment]
An idea I've been mulling (but not yet tried in code) is to use d3-force for the placement of labels.  The force would contain nodes representing each data point in the chart, plus nodes for the labels.
- There would be a layer added to the chart (like Semiotics annotation layer), which contains nodes for the data points (their position already set by whichever chart is being used) and labels for each data point
- The nodes for the  data points would have fixed position, and would not be visible, and would have some radius for collision detection 
- The nodes for the labels would be linked to their respective data point, with a relative high link strength
- The force algorithm would run prior to rendering the chart+labels, and so would not affect performance too much once the chart is rendered.
- Where overlaps occur, the user could specify which labels are displayed by default (eg highest values, min/max, with the rest available on hoverover of the data point)
I think this could work well for chart types such as scatters, networks, sankeys, radial (where the labels are on the circumference of the chart, especially at various radius)

This area examples which start to use this method, eg  http://bl.ocks.org/MoritzStefaner/1377729  or http://bl.ocks.org/pnavarrc/5913636, but which need some refinement.

D3-Labeler https://github.com/tinker10/D3-Labeler takes a different approach, but with similar results, and with the option to hide certain labels may work well too

**Comment by emeeks** [comment]
Ironically, a forceSimulation-based labeling system is already deployed in Semiotic, via the `annotationLayout` prop. But it's rudimentary and has lots of issues.

D3-Labeler looks like it would need to be forked but otherwise is a good prospect and I could see it useful across various data visualization modes, especially if it is part of an abstraction around the marks that lets the chart know what and where they are. @susielu has consistently asked for a solution that accounts for the data visualization elements themselves.

One of the biggest challenges and outstanding items is how to pass weights to labels/annotations and so on. For annotations they could simply be an additional prop, but how do we tell it to turn on labels and these labels or those labels are more important without making it so complex that people just ignore using it.

Thanks a bunch for the examples, if you have more, please post them.

**Comment by tomshanley** [comment]
For 'weights', do you mean how we tell the chart which labels we would prefer to be shown, in cases of too many overlapping labels?  Like 'All' 'Min/Max', 'Greater than X', 'Equal to X'. Conceivably, this option could just accept a user defined function, rather than providing prescribed options.

**Comment by emeeks** [comment]
Yes something like that. I just opened a `labella` branch to work on integrating labella in place of the marginalia calculations. If you'd like to jump into that or create a branch to hack at the existing annotationSettings, I'd love to have your input.

**Comment by emeeks** [comment]
Early results are promising.
<img width="473" alt="screen shot 2018-01-19 at 7 37 31 pm" src="https://user-images.githubusercontent.com/495634/35179490-3d4787c6-fd50-11e7-910c-bc0de09fc231.png">

**Comment by emeeks** [comment]
Labella has dramatically improved the marginalia annotation setting:
https://github.com/emeeks/semiotic/releases/tag/v1.5.2

I'm going to start a new branch and look into integrating `d3-labeler` code in place of the `forceSimulation` implementation in the bump annotation setting.

**Comment by emeeks** [comment]
d3-labeler code in 1.5.3 makes the bump annotations work better. Not great, but better. That covers the annotation improvements I wanted. When it comes to labels I'm not sure what the approach should be and how smart labels should be. I see labeled rectangles in bar charts, that seems pretty common, and curved labels on sunbursts and pie charts. But then you have to get to the point where you're trying to have smart labels that are aware of the Mark itself being rendered, otherwise it's just dozens of bespoke solutions wired together.
