### ISSUE TITLE
Common Chart Abstraction Components

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#115]
_Now that Semiotic has matured a bit and most of the bugs are ironed out I'm trying to think of ways to improve the library. Please thumbs up or thumbs down this if you think it would or wouldn't be useful. Also, if you have concerns or ideas, feel free to leave comments._

While I naturally want everyone to adopt my mental model for how charts are related, the various frames can be intimidating to new users. So maybe I should build a few components that have more friendly names and settings so people can finally have their `<PieChart>` and `<BarChart>`?

# Challenges
* How does one transition from a `<LineChart>` to an `<XYFrame>`?
* Besides convenience is there any opportunity for innovation?
* Could this be handled by rendering the Vega spec? (This is something I'd always planned to do with Semiotic)

**Comment by dgwyer** [comment]
I like the idea of abstracting the existing generic frames into more specific chart type components for easier consumption. I think it would help with adoption to some degree, as would a solid set of high quality standard example charts. Most people when they come across a new chart library head straight to the demos to check out what it's capable of.

I know Semiotic isn't meant to be just another charting library but people love chart candy (I know I do!), and if there's a great set of basic example charts available then that can only help.

It might be interesting to compile a set of charts using existing examples from various libraries as inspiration to test the flexibility of Semiotic. Ideally it should be able to recreate anything currently out there. I don't mind taking a look at this and reporting back about any issues, or if I'm struggling to implement something.

If I can't implement something then perhaps it's just the docs that need updating, or maybe a new feature needs adding. Whatever the root issue it could help to improve Semiotic by battle testing it against the baseline chart types.

Beyond the beginner, entry level charts, more advanced bespoke charts would follow on nicely to show off the power of Semiotic over other libraries (interaction, (advanced) annotation, combo charts, transitions between data sets and chart types and so on), as well as more examples of bespoke data visualizations (e.g. https://emeeks.github.io/semiotic/#/semiotic/regionatedlinechart).

Going a little off topic here, and it's not a priority in the short term, but I think the demo/docs site needs some work to make it more accessible/appealing. When I first looked at the examples I found the navigation a little confusing. Also, when clicking the "INTERACTIVE EXAMPLES" link on the home page takes a few seconds on my browser to load the examples page which isn't ideal (nothing happens for around 3-4 seconds before the examples appear). Again, other implementations could serve as inspiration as how to best present Semiotic to new users.

Hope this was helpful. I really like Semiotic and can see myself using it on a lot of projects so I'd like to see it more widely adopted, and I'm happy to contribute where I can! :)

**Comment by emeeks** [comment]
You make a couple really good points. Even without the abstraction of actual components, the documentation needs a serious overhaul. It needs to be split into sections so people can see basic charts without being overwhelmed by weird charts. And those charts need to show functionality in stepwise fashion.

The other side of the documentation, the wiki, also needs to be refreshed.

**Comment by dgwyer** [comment]
It might be worth considering in your YT videos to pick random examples of existing charts and try to recreate them using Semiotic. This could range from very basic charts that look great to more complicated examples.

I can't think of a better way to win people over to using a new library by demonstrating how flexible it is and how they can build something they already have in mind. It also could expose any areas of Semiotic that need work.

**Comment by emeeks** [comment]
I'll definitely do that next time. That was my motivation for the interactive examples so carrying it over to the livestreams makes a lot of sense.

**Comment by dgwyer** [comment]
Sounds great! :)
