### ISSUE TITLE
ORFrame.oExtent: Including a value in oExtent that isn't also in data results in error

### ISSUE THREAD

**Issue by AnkoNako** [emeeks/semiotic#116]
I have a chart using ORFrame with the "swarm" type.  The "oAccessor" points to an attribute that has all values from 26 to 42, **except for 41**.  So the ordinal axis skips from 40 to 42.

I attempted to use oExtent to include "41" in the oAxis:
`oExtent={[26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42]}`

But this resulted in a error on ORFrame.js:
`node_modules/semiotic/lib/ORFrame.js:373`
`TypeError: Cannot read property 'forEach' of undefined`

Thanks!

**Comment by emeeks** [comment]
The ordinal values are cast into strings, so could you try that but with quotes around each of your numbers?

**Comment by AnkoNako** [comment]
Still the same error.  It looks like it's erroring on this line in ORFrame.js:
`projectedColumns[o].pieceData.forEach(function (piece) {`

So the oExtent value of "41" is properly creating a `projectedColumn` with a name of "41", but that `projectedColumn` doesn't have any `pieceData` associated to it.

If you want to look at the chart code I'm using, feel free: 
https://github.com/AnkoNako/semiotic-examples/blob/master/src/FreeAgentsBoard.js

**Comment by emeeks** [comment]
I see what you mean. I'll correct this, thanks for finding it.

**Comment by emeeks** [comment]
This should be fixed in 1.5.1, let me know if you have a chance to try it, I tested it and it seems to be working in all the cases I tested.

**Comment by AnkoNako** [comment]
Yep, after upgrading to 1.5.1, no more error and works as expected .  Thanks for fixing!
