### ISSUE TITLE
Add unpkg info to GitHub readme

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#119]
Now that Semiotic is available via unpkg:

e.g. `https://unpkg.com/semiotic@1.5.2/dist/semiotic.min.js`

can this info be added to the installation instructions on the Semiotic GitHub readme? I think it would be useful for users to know that they can just drop in the unpkg URL to any page and instantly have Semiotic available.

Also, I just found out that if you use:

`https://unpkg.com/semiotic/dist/semiotic.min.js`

then this _always_ resolves to the latest version of Semiotic. Very useful if you have tons of examples on CodePen or bl.ocks.org as this means you won't have to go back and manually update the Semiotic URLs to the latest version!

Example of using the latest version URL (see pen JS settings): `https://codepen.io/dgwyer/pen/9307ecc38051fa69830709748c52d065`

Also, would it be a good idea to add some new labels for Wiki docs, Github readme, and main <a href="https://emeeks.github.io/semiotic">Semiotic site</a> to help organize GitHub issues?

As d3 is frequently used alongside Semiotic it might be worth mentioning that you can do a similar thing to always load the latest version of d3 using:

`https://unpkg.com/d3/build/d3.min.js`

If you visit this URL in the browser it (like the Semiotic URL) resolves to the latest version URL.

e.g. `https://unpkg.com/d3@4.12.2/build/d3.min.js`

You can also do similar with React and ReactDom. So to always use the latest versions of Semiotic, d3, React and ReactDom use:

`https://unpkg.com/semiotic/dist/semiotic.min.js`
`https://unpkg.com/d3/build/d3.min.js`
`https://unpkg.com/react/umd/react.production.min.js`
`https://unpkg.com/react-dom/umd/react-dom.production.min.js`

**Being able to always use the latest versions of Semiotic, d3, react and ReactDom in pens, bl.ocks.org etc. is a great timesaver!**

**Comment by emeeks** [comment]
Thanks, David, these are all very good points. Any suggestions for labels, tags, categories and structure of the documentation are very welcome.

**Comment by dgwyer** [comment]
I think adding labels similar to:

* `wiki docs`
* `semiotic docs` (for the main Semiotic site)
 
would be helpful to start with to organize and search for doc related issues.
