### ISSUE TITLE
Update needed for "Visualizing Time Series Data" wiki page?

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#120]
I was taking a look at the **Visualizing Time Series Data** wiki page. In the [Visualizing Data with Dates](https://github.com/emeeks/semiotic/wiki/Visualizing-Time-Series-Data#visualizing-data-with-dates) section is the declaration of the `Date()` objects correct?

I could only get it to work when `Date()` was preceded by `new` as follows:

```JavaScript
const data = [
    { id: 'linedata-1', color: '#00a2ce', 
       data: [ 
            { sales: 500, timestamp: new Date(2017, 7, 1) }, 
            { sales: 700, timestamp: new Date(2017, 7, 2) }, 
            { sales: 0, timestamp: new Date(2017, 7, 3) }, 
            { sales: 0, timestamp: new Date(2017, 7, 4) }, 
            { sales: 200, timestamp: new Date(2017, 7, 5) }, 
            { sales: 300, timestamp: new Date(2017, 7, 6) }, 
            { sales: 500, timestamp: new Date(2017, 7, 7) } 
           ] 
    }
]
```

See the 'Time Series' chart [here](https://codepen.io/dgwyer/pen/OzYvOP) for an example implementation of this working.

**Comment by emeeks** [comment]
Thanks for catching this, it's fixed now.
