### ISSUE TITLE
How to use the <Mark /> component in CodePen and bl.ocks.org

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#121]
I'm trying to create custom point marks for a multi-series line chart using <a href="https://github.com/emeeks/semiotic/wiki/XYFrame#custompointmark--jsx--function-
">`customPointMark`</a>.

However, I'm unsure of how to include the [`<Mark />`](https://github.com/emeeks/semiotic/wiki/Mark) component in online developer playgrounds such as CodePen and bl.ocks.org.

I've set up a [pen](https://codepen.io/dgwyer/pen/ccf29f8816a019ca50caa78a46b21e78/) to test this. I just need to know how to import the `<Mark />` component. Do I use the following URL to access the API: https://unpkg.com/semiotic-mark/lib/Mark.js

If so then how can I make it available via JS? I tried `const { Mark } = Mark;` but it didn't work.

Perhaps the docs for [`<Mark />`](https://github.com/emeeks/semiotic/wiki/Mark) could be updated to include the necessary information?

**Comment by emeeks** [comment]
Unfortunately there's no build process to get the `semiotic-mark` dist up onto unkpg like there is for Semiotic. I don't plan to do that, either, as my plans for `semiotic-mark` are to go in a different direction for it. Instead, I think I'll expose it via the Semiotic library by importing it from semiotic-mark and exporting it via semiotic. That doesn't help folks who want to use it outside of Semiotic but I doubt that's a major use case, anyway.

**Comment by dgwyer** [comment]
Ah OK. So once semiotic-mark is exported via semiotic we could access `<Mark />` via:

`const { ORFrame, XYFrame, NetworkFrame, Mark } = Semiotic;`

Is that correct?

**Comment by emeeks** [comment]
That's right. I'll probably be publishing 1.5.3 tomorrow and that will expose it.
