### ISSUE TITLE
Allow axis label.name to be JSX object

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#124]
I'm trying to add an axis label **Temperature (&#176;C)**. At the moment you can only specify a string for the axes labels:

```JSX
<Axis label="Units Sold" />
```

or

```JSX
<Axis label={{ name: "Units Sold" }} />
```

If you try to insert an HTML symbol such as `&#176;` (&#176;), or  a `<tspan>` element, the markup is outputted instead.

It would be very useful if `label` and/or `label.name` could optionally be a JSX object (similar to the [XYFrame title](https://github.com/emeeks/semiotic/wiki/XYFrame#title--string--jsx-) property).

This would allow you to directly insert HTML symbol characters and have more precise control over the SVG `<text>` element that renders the axis label so you could add in extra markup. e.g. `<tspan>` elements to help output simple math expressions.

**Comment by emeeks** [comment]
1.5.3 will allow label/label.name to be JSX SVG.
