### ISSUE TITLE
Multiple axis baselines rendered per axis orientation

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#125]
The axis baselines are being rendered each time per axis orientation.

e.g. The following will result in three y-axis baselines being rendered.

```jsx
    axes={[
      { orient: "left", label: "Temperature" },
      { orient: "left", tickFormat: () => '', tickSize: 3 },
      { orient: "left", tickFormat: () => '', tickSize: -3 },
    ]}
```
The following screenshot shows the duplicate markup being outputted.
![multiple-main-axis-lines1](https://user-images.githubusercontent.com/1482075/35389827-169b9bdc-01d1-11e8-8393-d9cf3e1fdc0b.png)
Ideally, there should only be one axis baseline rendered per orientation regardless of the number of axis definitions.

If this can't be done automatically then I'd suggest perhaps adding adding a boolean `axisBaseline` property to `<Axis />` so we could switch it off on a per axis basis?

**Comment by emeeks** [comment]
As of 1.6.0 this `<Axis>` will accept a `baseline` prop (default to true) and `<XYFrame>` and `<OrdinalFrame>` will by default set the baseline prop of the overlapping axis elements to false unless the user specifies baseline: true in their object.

Will close this when 1.6.0 is published.
