### ISSUE TITLE
Broken link in XYFrame wiki docs

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#126]
In the [lineType](https://github.com/emeeks/semiotic/wiki/XYFrame#linetype--string--object-) section the "line types" link just points to the same page.

Either the link is broken or the intended page hasn't been written yet.

**Comment by emeeks** [comment]
Thanks, it should have pointed to this: https://github.com/emeeks/semiotic/wiki/lineType-Advanced-Settings
