### ISSUE TITLE
Duplicate entry in <Legend /> wiki for 'width' under API Reference

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#127]
https://github.com/emeeks/semiotic/wiki/Legend#width--number-

**Comment by bengarvey** [comment]
@dgwyer Fixed. Anyone can edit the wiki btw.

**Comment by dgwyer** [comment]
@bengarvey Thanks. I literally didn't know that until now. Will save posting  a lot of issues for simple fixes!
