### ISSUE TITLE
Conditional styling of tick labels in an XYFrame

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#128]
I can do this in an ORFrame and oLabels like this:

```
oLabel={(d, i) => (<text x={0} y={3} className={i[0].className} textAnchor="end">{d}</text>)}
```

Example - Coloring female directors in my movie list
![screen shot 2018-01-25 at 8 47 22 pm](https://user-images.githubusercontent.com/1342331/35421409-11ef9ec2-0211-11e8-9dbe-65ecc5c4a08e.png)

But in an XYFrame, I don't think there's a way to conditionally set a class, because className only accepts a string. Is there?
```
axes={[
  { className: 'slopeTick', orient: 'left', tickFormat: d => d, ticks: 10}
]}
```

Use case - I want to color movie titles red in this slope chart that are not included on the right side.
![screen shot 2018-01-25 at 8 47 34 pm](https://user-images.githubusercontent.com/1342331/35421423-2c8d89ec-0211-11e8-94b1-d9b872a7f1bc.png)

**Comment by emeeks** [comment]
`Axis.tickFormat` allows you to return SVG JSX:

`tickFormat: d => <text style={{ fill: "red" }}>{d}</text>`

Let me know if that's not what you mean.

**Comment by emeeks** [comment]
Notice that when you do that you'll need to set the textAnchor prop for left axes (and probably otherwise adjust them a little).

**Comment by bengarvey** [comment]
It's less than ideal since I have to use a lookup table instead of having the whole object to work with (d is the tick label in this case, not the data object), but that worked for me. Thanks!
![screen shot 2018-01-26 at 8 23 27 am](https://user-images.githubusercontent.com/1342331/35441662-5fb30a20-0272-11e8-9b77-e70f817d854e.png)

**Comment by bengarvey** [comment]
Sneak preview:
http://plotdevice.bengarvey.com/movies

**Comment by emeeks** [comment]
Ah I see what you mean @bengarvey, I'll see if there's any way to pass the data. I don't think so, at least not unless we revisit what an axis means (which is feasible) since it gets preprocessed and any data-related bits get stripped out and only the label remains. But for charts like those it does seem necessary. Will think about it.

**Comment by dgwyer** [comment]
@bengarvey That looks pretty cool. Is there any chance I can take a look at the Semiotic code used to create that?

**Comment by bengarvey** [comment]
@dgwyer Sure. The code is gnarly at the moment but it will look better by the time I merge it to master.
https://raw.githubusercontent.com/bengarvey/plotdevice/movies/src/components/Movies.js

**Comment by dgwyer** [comment]
@bengarvey Thanks. 👍

**Comment by emeeks** [comment]
@bengarvey If you see any patterns that you think would help to be exposed in a reusable way to make charts like these easier, let me know.
