### ISSUE TITLE
Cannot get time series example to work when using dates.

### ISSUE THREAD

**Issue by grady-lad** [emeeks/semiotic#13]
Hey great work on the lib, it looks really promising. 

I tried to go through the example which i found [here](https://github.com/emeeks/semiotic/wiki/Visualizing-Time-Series-Data).

Which was working fine when using the dataset without any dates, but when I switched over to using the dataset with dates I received the error below which I found hard to trace. 

<img width="1438" alt="screen shot 2017-09-05 at 23 25 50" src="https://user-images.githubusercontent.com/6424060/30084219-cf21e076-9291-11e7-8750-7615c59eb3be.png">

This is the snippet I was using 

````javascript

// data for the graph
const data = [
    { id: 'linedata-1', color: '#00a2ce',
       data: [
            { sales: 500, timestamp: Date(2017, 7, 1) },
            { sales: 700, timestamp: Date(2017, 7, 2) },
            { sales: 0, timestamp: Date(2017, 7, 3) },
            { sales: 0, timestamp: Date(2017, 7, 4) },
            { sales: 200, timestamp: Date(2017, 7, 5) },
            { sales: 300, timestamp: Date(2017, 7, 6) },
            { sales: 500, timestamp: Date(2017, 7, 7) }
           ]
    },
]
//graph div
<XYFrame
    size={[500, 700]}
    lines={data}
    xAccessor="timestamp"
    yAccessor="sales"
    xScaleType={scaleTime()}
    lineDataAccessor="data"
    lineStyle={d => ({ stroke: d.color, fill: d.color })} />
````

**Comment by emeeks** [comment]
If you use `Date(x)` it gives you a string date, what you want to use is `new Date(x)` which will give you a js Date object.
