### ISSUE TITLE
NetworkFrame nodeLabels errors when taking a function 

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#130]
This works for my sankey diagram

```
    <ResponsiveNetworkFrame
        size={[ 300, 700 ]}
        responsiveWidth={true}
        edges={network.links}
        nodes={network.nodes}
        nodeStyle={d => ({
          fill: d.fill,
          stroke: d.stroke
        })} 
        edgeStyle={(d) => ({ stroke: d.stroke, fill: d.fill, opacity: 0.5, strokeWidth: '1px' })} 
        networkType={{ type: 'sankey', orient: 'center', iterations: 500 }}
        nodeIDAccessor={"id"}
        zoomToFit={true}
        nodeLabels={d => d.name}
        sourceAccessor={"source"}
        targetAccessor={"target"}
        nodeSizeAccessor={d => d.size}
        margin={{left: 25, top: 20, bottom: 20, right: 25}}
    /> 
```
and produces this. 
![screen shot 2018-01-27 at 8 31 17 pm](https://user-images.githubusercontent.com/1342331/35478071-602447b4-03a1-11e8-93c9-a679fa822808.png)

I want to shift the labels over to the right, but when I try to change the nodeLabels to something like this:

```
nodeLabels={d => <text textAnchor="right">{d.name}</text>}
```

I get the following build error `text.split is not a function`
![screen shot 2018-01-27 at 8 36 17 pm](https://user-images.githubusercontent.com/1342331/35478082-c9d32f9a-03a1-11e8-87eb-8fa6a5556d05.png)

Any ideas? This also happens with the force layout.

**Comment by bengarvey** [comment]
Also, I don't think the sankey diagrams resize in the ResponsiveNetworkFrame, but that's another issue :)

**Comment by emeeks** [comment]
Labels in NetworkFrame are technically annotation elements. It made them automatically honor `annotationSettings` but at the cost of not following the same patterns elsewhere, especially given that you could do functionally the same thing by mapping nodes to annotations. It was, I think, a bad decision and one which I am going to change in 1.6. I'll also check on the sankey diagrams.

**Comment by emeeks** [comment]
@bengarvey Going to close this could you open a new one with the sankey resizing?
