### ISSUE TITLE
Specifying point marks for series data

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#131]
I've been experimenting with adding custom point marks for line series data. See example pen here:

https://codepen.io/dgwyer/pen/GyaYJy

I added the point mark values directly into the data set to make it easier to specify which point mark to use for each series. However, this isn't ideal.

Would it be possible to send details of the current series being iterated over to the `customPointMark` prop. The data series name, and index in-particular, would be most useful. That way it would be fairly easy to add a lookup table to store which custom point marks to display for each series.

Also, if this was available in the `pointStyle` prop too then you could achieve a similar thing with colors for each series. At the moment I'm adding the color directly in the data for each series.

I'd rather not specify series attributes in the data so I think this would really help.

Also, in the pen above I've implemented some custom marks manually. Are there any plans to add a set of built-in marks that we can easily consume for point series data? It would be nice to have a full set to use out of the box.

Also, in the future custom graphics for point marks would be cool. e.g. https://abtsoftware-wpengine.netdna-ssl.com/wp-content/uploads/2016/02/scichart-wpf-chart-example-using-pointmarkers.png

**Comment by emeeks** [comment]
XYFrame has a `showLinePoints` prop that turns on the points used to construct a line. These points are subject to `customPointMark` which can be used to specify different graphics for points, but keep in mind that `customPointMark` sends `({ d })` and not `(d)` but if you use the function, points that are part of a line have a `parentLine` property. Here's I'm styling Arsenal with a square and Everton with a rectangle:

<img width="443" alt="screen shot 2018-01-28 at 3 31 14 pm" src="https://user-images.githubusercontent.com/495634/35488655-a7639b12-0440-11e8-9268-9d4797d933ce.png">

You could also pass an svg `<image>` if you want thunderclouds. Here's the pen:
https://codepen.io/emeeks/pen/bLbzJM

**Comment by emeeks** [comment]
I'm going to assume that worked and close this, if you're having further issues or you think the API could be improved feel free to comment and/or reopen.
