### ISSUE TITLE
how to use sparklines

### ISSUE THREAD

**Issue by rinaldi6109** [emeeks/semiotic#134]
Can you indicate me the document which explains how to use sparklines, as in this image?
[img](https://user-images.githubusercontent.com/495634/35601536-755bfc0a-05e8-11e8-9c8e-00d7f96109ba.png)
Thank you.

**Comment by emeeks** [comment]
Yes, I'm half in and half out of updating all the documentation and so as a result the Sparkline documentation wasn't properly published. I went ahead and updated it:

https://emeeks.github.io/semiotic/#/sparkline
https://github.com/emeeks/semiotic/wiki/SparkXYFrame
https://github.com/emeeks/semiotic/wiki/SparkOrdinalFrame
https://github.com/emeeks/semiotic/wiki/SparkNetworkFrame

**Comment by emeeks** [comment]
Here's a livestream about it:
https://www.youtube.com/watch?v=wCAhkIMT464

And the codepen it references:
https://codepen.io/emeeks/pen/BYjZeZ
