### ISSUE TITLE
Typings

### ISSUE THREAD

**Issue by fuocor** [emeeks/semiotic#137]
Hi folks, great work... 
I was wondering where I can get the type files for the package.

rich

**Comment by emeeks** [comment]
I haven't worked with any of the typed javascript forms, so I wouldn't even know where to start with this. However, if someone wants to put this together, once I see the pattern, I'll make sure to maintain it.

**Comment by fuocor** [comment]
Hi,

I started typing the XYFrame for my requirements based on your documentation and source. When I am comfortable with the outcome, I'll forward you the results. The challenge is safely typing it without reverting to any for the data structures you pass to the property call-backs.

rich

**Comment by emeeks** [comment]
Great! I can see how it would be challenging, let me know how I can make it easier.

**Comment by chadbr** [comment]
All I can add here is a "please?" :)

**Comment by emeeks** [comment]
So there's a lot of flow in here now and I'm closing this issue because of that. If we want to address specific issues around typing those can be raised separately.
