### ISSUE TITLE
Problem with the data-visualization not updating

### ISSUE THREAD

**Issue by fuocor** [emeeks/semiotic#138]
I have the following code where (Chart is XYFrame)

```
           <div className={ css("chart", styles.root) }>
                { values.length && <Chart
                    name={ "LoadForecast" }
                    title={ "Aggregate Feeder Load" }
                    dataVersion={ version }
                    size={ [720, 480] }
                    lines={ values }
                    lineType={ { type: "line", interpolator: curveCardinal } }
                    showLinePoints={ false }
                    pointStyle={ pointStyle }
                    hoverAnnotation={ true }
                    xAccessor="x"
                    yAccessor="y"
                    lineIDAccessor="lineId"
                    renderKey={ (d: ILine) => d.lineId }
                    lineStyle={ lineStyle }
                    margin={ { left: 80, bottom: 50, right: 10, top: 40 } }
                    axes={ [
                        { orient: "left", tickFormat: (d: number) => { return this._yAxis(d); } },
                        { orient: "bottom", tickFormat: (d: number) => { return this._xAxis(d); } }
                    ] }
                />
                }
            </div>
```

in the render of the VisualizationLayer I trace out a portion of the line path and see the following as the data is updated.

```
11:13:49 ForecastChart.render: version 2 
11:13:51 MapView.aggregateResults has 1093 entries 
11:13:51 ForecastChart.render: version 2 
11:13:51 ForecastChart.render: version 3 
M0,23.783048947722307C0,23.783048947722307,18.26086956521739,37.1592662957539,27.391304347826086,38.99181192678833C36.52173913043478,40.82435755782276,45.652173
11:14:04 ForecastChart.render: version 3 
11:14:05 MapView.aggregateResults has 325 entries 
11:14:05 ForecastChart.render: version 3 
11:14:05 ForecastChart.render: version 4 
M0,32.54675912219312C0,32.54675912219312,18.26086956521739,35.45645094147448,27.391304347826086,37.008685823304916C36.52173913043478,38.56092070513535,45.652173
11:14:07 ForecastChart.render: version 4 
11:14:07 MapView.aggregateResults has 503 entries 
11:14:07 ForecastChart.render: version 4 
11:14:07 ForecastChart.render: version 5 
M0,23.12262838649849C0,23.12262838649849,18.26086956521739,34.28596099435074,27.391304347826086,36.35530910226447C36.52173913043478,38.424657210178204,45.652173
11:17:56 PageHeader.backgroundImage changed: page_header_cellimage_20_9Y_C8 
11:18:08 ForecastChart.render: version 5 
11:18:08 MapView.aggregateResults has 698 entries 
11:18:08 ForecastChart.render: version 5 
11:18:08 ForecastChart.render: version 6 
M0,22.96754855022232C0,22.96754855022232,18.26086956521739,39.53815848772094,27.391304347826086,41.74608858791504C36.52173913043478,43.95401868810914,45.6521739
```
Unfortunately, everything else updates (axis, and hover annotations) but not the line paths.  

in chrome it is stuck at 
```
M0,23.783048947722307C0,23.783048947722307,18.26086956521739,37.1592662957539,27.391304347826086,38.99181192678833C36.52173913043478,40.82435755782276,45
```

Any help is really appreciated.
rich

**Comment by emeeks** [comment]
Hard to tell without seeing the data. If you could post it on a gist that would be great. Otherwise, I'd try to skip the `dataVersion` setting if there's any way at all that you can ensure that all the props being sent to your frame are fixed and not inline. In other words, build all the settings outside the render function and pass them down so they aren't constantly changing. That said, I'd be happy to take a look if you can send me the data or a dataset that causes the same issues with those settings, as well as when and how you're calculating the value that you're sending to `dataVersion`.

**Comment by fuocor** [comment]
[semiotic.zip](https://github.com/emeeks/semiotic/files/1704555/semiotic.zip)


I attached a zip with a source that reproduces the problem.
Just do the following after unzipping
```
npm install
nmp build
nmp run start
```
then open your browser to http://localhost:8080

rich

**Comment by fuocor** [comment]
So... it appears if the ```renderKey``` property reuses the same values, then React will not render the child element even if the path has changed. 
In my sample changing 
```renderKey={(d: ILine) => d.lineId}```
to
```renderKey={(d: ILine) => `${d.lineId}${version}`}```
solves the issue

**Comment by fuocor** [comment]
The problem with the ```key``` also occurs on the tick lines which do not update. 
In the sample I provided changing the tick-line style to displaying the stroke will demonstrate the problem

rich

**Comment by emeeks** [comment]
Thanks for digging into this, I'll take a look at your example and see what I can do to make it work more cleanly.

**Comment by brianretford** [comment]
+1  on this, needed to do exactly this
