### ISSUE TITLE
ResponsiveOrdinalFrame sketchy forever rendering

### ISSUE THREAD

**Issue by puria** [emeeks/semiotic#140]
Hi,

When a window resize occurs on a ResponsiveOrdinalFrame it will be re-rendered forever that is quite cool in sketchy mode... but maybe a not wanted behaviour.

a codepen here to try
https://codepen.io/pna/pen/zRNgxo?editors=0011

![codepen](https://user-images.githubusercontent.com/10379/36023584-39e7eb46-0d8d-11e8-9876-f5ab4fd3d733.gif)

![out](https://user-images.githubusercontent.com/10379/36023311-4d3af1d0-0d8c-11e8-8030-0f93e115d6bc.gif)

**Comment by emeeks** [comment]
Will take a look.

**Comment by emeeks** [comment]
I couldn't reproduce this:
https://codepen.io/emeeks/pen/PQpRdR

And it also doesn't seem to happen when I check your codepen. Is there anything else going on that I'm not seeing?

**Comment by puria** [comment]
Noticed that is happening, not on resize actually, but when the scrollbar is not there anymore... `windowHeight >= 100%` maybe?

**Comment by ZachHaber** [comment]
This actually happened to me as well. I just checked out a hunch about it, and it seems to occur in Chrome and not in Firefox.

**Comment by emeeks** [comment]
Maybe it's some kind of loop where the scrollbar disappearing makes it resize and then it resizes just enough to bring the scrollbar back?

**Comment by emeeks** [comment]
This seems like it's no longer happening since the update to Rough.js but feel free to reopen if you can reproduce.
