### ISSUE TITLE
MinimapXYFrame: "TypeError: Cannot read property 'selection' of null"

### ISSUE THREAD

**Issue by infograafikko** [emeeks/semiotic#144]
I am trying to get this example to work: https://emeeks.github.io/semiotic/#/semiotic/minimap

However I get this error message:
```
TypeError: Cannot read property 'selection' of null
SVGGElement.<anonymous>
node_modules/semiotic/lib/InteractionLayer.js:172
  169 | }
  170 | 
  171 | semioticBrush.extent([[0, 0], [this.props.size[0], this.props.size[1]]]).on("start", function () {
> 172 |   _this2.brushStart(mappingFn(_d3Selection.event.selection));
  173 | }).on("brush", function () {
  174 |   _this2.brush(mappingFn(_d3Selection.event.selection));
  175 | }).on("end", function () {
```

Any idea what can cause this kind of problem? I am using [this dashboard bootstrap](https://www.creative-tim.com/product/light-bootstrap-dashboard-react) as a template and other Semiotic visualizations work well.

**Comment by emeeks** [comment]
The brush in Semiotic will run into a [known issue with d3.event that crops up in certain builds](https://github.com/d3/d3/issues/2733). You'll have to dig into your build process to resolve it. I'm not sure how the template is being built but the problem is somewhere in there.

**Comment by RMKD** [comment]
This issue is still occurring for me with create-react-app (`react ^16.2.0`, `semiotic ^1.8.3`). Perhaps someone can document a solution?

**Comment by emeeks** [comment]
It unfortunately has nothing to do with the version of Semiotic or React but rather the settings in your build process. I'm not clear enough on when it happens to document a solution, though.

**Comment by brianretford** [comment]
This seems to be caused by semiotic having it's own copies of d3 inside it's npm package. If I remove them, everything works fine.
