### ISSUE TITLE
Dynamically generated frame key causing error in WordPress block

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#145]
I'm trying to get a Semiotic chart working inside a WordPress Gutenberg block. The WordPress editor will undergo a major update when WordPress v5.0 is released. Posts will be made up of blocks which can be any content you like.

I've created a test block to display a basic chart taken from one of your early CodePen examples: https://codepen.io/emeeks/pen/KyovjB?editors=1010

I can get the chart to display OK but there's an issue with the dynamically generated frame key on the XYFrame. WordPress validates saved blocks against the generated markup in the editor on page load and if there are any discrepancies then an error is thrown.

Because the frame key is dynamically generated every time the XYFrame is displayed this causes an error inside the WordPress editor.

https://github.com/emeeks/semiotic/blob/413839c68030bef3ba6db312dc9db03fcd5b3eb9/src/components/XYFrame.js#L58

Are there special considerations for the frame key that means it has to be dynamically generated? Would a way around this be to make the frame key a prop so it could be set manually? And if it's not set then it should be dynamically generated as it currently is?

I encountered this for the XYFrame but will probably also be the case for other frame types too.

![different-frame-keys](https://user-images.githubusercontent.com/1482075/36276616-6e3ab286-1286-11e8-88f2-08aeef971204.png)

**Comment by dgwyer** [comment]
Here's a preview of the chart rendering in the new Gutenberg editor. It renders fine but when the page refreshes an error is thrown due to the saved frame key not matching the frame key when the chart is re-rendered on page load.

![gb-test-chart](https://user-images.githubusercontent.com/1482075/36276995-7859dd0e-1287-11e8-972b-09c85f99ab39.png)

**Comment by emeeks** [comment]
I'll add an override into the next version so if you send a frameKey then it will overwrite the generated one and I added some code so that if you're not turning on a matte it won't even do it (because that's the only time you need a key).

I hope to publish the fix tomorrow.

**Comment by dgwyer** [comment]
That would be brilliant, thanks.

**Comment by emeeks** [comment]
This update is in 1.7.11.

**Comment by dgwyer** [comment]
This update fixes the reported issue in the XYFrame.

Just wondering, do the other frames need a `frameKey` prop adding too or was this unique to the XYFrame?

**Comment by emeeks** [comment]
This was unique to XYFrame due to a clip behavior that only happens in that frame. In the other frames, the matte only covers the elements (as it mostly only does in XYFrame).

**Comment by dgwyer** [comment]
👍
