### ISSUE TITLE
Canvas too large on v 1.7.9

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#146]
Canvas size extending beyond the size of the frame.

![screen shot 2018-02-15 at 2 49 37 pm](https://user-images.githubusercontent.com/1449837/36285206-7c7a9d9c-125f-11e8-82d1-17969f344e05.png)

**Comment by susielu** [comment]
It is covering the hover region for some of my interactive elements.

**Comment by emeeks** [comment]
Fixed in 1.7.10
