### ISSUE TITLE
WordPress Gutenberg not rendering chart data points on front end

### ISSUE THREAD

**Issue by dgwyer** [emeeks/semiotic#149]
I've created a WordPress Gutenberg block to render a simple chart in the new editor. This renders fine in the editor, but when viewing the chart on the front end the data points are missing.

The whole SVG group for the data points is not present inside the chart SVG element. It's as though they were not added at all.

![gb-chart-no-data-points](https://user-images.githubusercontent.com/1482075/36341495-02ecc84a-13e7-11e8-8875-d810169345ad.png)

I'm not sure where to start looking for what could be causing this. As far as the Gutenberg editor goes the `<XYFrame ... />` component is just another component that should be rendered exactly the same on the editor and front end.

The axis labels, and tick lines render fine on the editor and front end so why not the data points too?

I'll open an issue with the Gutenberg editor too but is there anything to do with the way data points are rendered in Semiotic that could possibly explain this?

**Comment by emeeks** [comment]
Is there any way to point me at the page you're working on or a way for me to reproduce it?

**Comment by dgwyer** [comment]
[wpgo-semiotic-test.zip](https://github.com/emeeks/semiotic/files/1737928/wpgo-semiotic-test.zip)

Sure Elijah. I've added a test plugin so you can reproduce via the following steps:

1. Install/activate the latest version of WordPress and the Gutenberg [plugin](https://wordpress.org/plugins/gutenberg/).
2. Install/activate the **Semiotic Test** WordPress plugin. (see the attached plugin zip file)
3. Create a new page and in the new (Gutenberg) editor add a **Semiotic Test** block. You can start typing Semiotic to show the block so you can insert it.
4. Once inserted you should see a basic scatter chart in the editor as in my previous screenshot.
5. Save the page and then view on the front end. You should see the chart minus that data points.
6. The code that adds the chart component is in `./src/block/block.js` inside the plugin folder.
7. If you wish to edit the code then run `npm install` and then `npm start` which will recompile the JSX. You'll need to empty your browser cache and reload the page to see changes.

Hopefully that is enough to reproduce the issue I'm seeing my end. Please let me know if you need any more details.

**Comment by dgwyer** [comment]
A new version of the Gutenberg WordPress plugin has just been released and I'm happy to say that after (a very quick) test the chart data appears to persist when viewing the chart on the front end too!

**Comment by emeeks** [comment]
Oh excellent!
