### ISSUE TITLE
Add ESLint config file

### ISSUE THREAD

**Issue by netbek** [emeeks/semiotic#151]
`npm run lint` fails because ESLint can't find a config file.

Here's a modest fix: [PR](https://github.com/emeeks/semiotic/pull/150)

**Comment by netbek** [comment]
Closed because merged: https://github.com/emeeks/semiotic/pull/150

**Comment by emeeks** [comment]
Thanks, I obviously never ran `npm run lint`. I merged and updated the rules a bit and then linted all the gunk out of my code.
