### ISSUE TITLE
[Docs] Basic Pie Chart Code Incorrect

### ISSUE THREAD

**Issue by bloomdido** [emeeks/semiotic#154]
The basic pie chart documentation has the following sample code:

```
const colorMap = {
  5: '#00a2ce',
  8: '#4d430c',
  10: '#b3331d',
  15: '#b6a756'
};
const data = [ 5, 8, 10, 15 ]

 <OrdinalFrame
    size={[ 700,400 ]}
    data={data}
    projection={"radial"}
    style={d => ({ fill: colorMap[d.value], stroke: "darkgray", strokeWidth: 1 })}
    type={{ type: "bar", innerRadius: 0 }}
    oLabel={true}
    dynamicColumnWidth={d => d.value}
    rAccessor={() => 1}
    margin={{ left: 20, top: 20, bottom: 20, right: 20 }}
    oPadding={0}
    tooltipContent="pie"
    hoverAnnotation={true}
  />
```

However, it appears (after quite a bit of frustration) that the correct definition for `dynamicColumnWidth` should be:

```
    dynamicColumnWidth={d => d[0].value}
```

I'm guessing that changed in a recent release...

**Comment by emeeks** [comment]
You're right the documentation is incorrect and I'm sorry about that. `dynamicColumnWidth` sends an array of values for that column that you can operate on in whatever manner you want. If you send it a string it will base column width on the sum of that property's value for that column. So this should have been what the code said:

```
dynamicColumnWidth="value"
```

But for other viz you might want to base the size on the max or average value, in which case use a function like you did and compute the max or average.

I'll make sure to fix the docs for the pie chart interactive example.
