### ISSUE TITLE
Bug: Hover regions not clipped by matte

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#156]
I have some buttons below my chart area in the foregroundGraphics, but when the chart is zoomed in and there is a matte the voronoi interaction is taking precedence over the interaction of buttons in the foregroundGraphics.

![screen shot 2018-02-20 at 9 46 51 am](https://user-images.githubusercontent.com/1449837/36439952-46f81ec0-1623-11e8-93b6-bb3c63c4ef54.png)
![screen shot 2018-02-20 at 9 47 16 am](https://user-images.githubusercontent.com/1449837/36439986-5a8090a8-1623-11e8-9cba-08c181a3abf9.png)

**Comment by emeeks** [comment]
I added some code to clip out the points used to generate the overlay that are outside of the canvas.

**Comment by emeeks** [comment]
Will be out with the next release.

**Comment by susielu** [comment]
Thanks Elijah!
