### ISSUE TITLE
Highlight a region in an XYFrame

### ISSUE THREAD

**Issue by jhvanderven** [emeeks/semiotic#159]
I am looking for a solution for the following viz:
0) I have something akin to small multiples for each day of the month
In each small multiple I'd like to show
1) A timeline showing the production of something (I can do this with an XYFrame) for the whole month
2) Highlight the production of that specific day by showing a different background color for that specific region of the frame (which I don't know how to do)

I was looking into annotations and overlapping frames (position:absolute won't do I think), but I could not figure it out.

Any help will be appreciated.
Pointers too.

**Comment by jhvanderven** [comment]
To answer myself, I managed to get the viz working with another xy dataset in the lines collection:
                {dt:this.props.date,v:ymin},
                {dt:this.props.date,v:ymax},
                {dt:moment(this.props.date).add(1,'d'), v:ymax},
                {dt:moment(this.props.date).add(1,'d'), v:ymin},
                {dt:this.props.date, v:ymin},
If you put this first (so it gets rendered first) and give it a different stroke color it kinda works. Snazzy would be an transparent rect with these coordinates in the same frame.

**Comment by emeeks** [comment]
Hard for me to visualize, could you post a screenshot? I'm planning for a small multiples feature so maybe this is something I can help automate.

**Comment by jhvanderven** [comment]
![screen shot 2018-02-25 at 10 52 39](https://user-images.githubusercontent.com/2427214/36640164-336b62fe-1a1a-11e8-9d10-82b07c35537b.png)
The idea is to have one 'tile' for each day of the selected period. On that tile I want to highlight that day's production in the context of the whole time interval. The small grey rectangle does the job, but I was thinking about a semi-transparent coloured rectangle.

**Comment by emeeks** [comment]
Take a look at the "dot com bubble" annotation in this example: https://emeeks.github.io/semiotic/#/semiotic/annotations

The format of that annotation is:
```
{
    className: "dot-com-bubble",
    type: "bounds",
    bounds: [{ date: new Date("1/2/1997") }, { date: new Date("1/2/2001") }],
    label: "The dot-com bubble",
    dx: 350
  },
```

And the gradient fill is done with CSS.

I still might not quite understand what you mean, though, so feel free to give more context.

**Comment by jhvanderven** [comment]
That's exactly what I was looking for.
![screen shot 2018-02-26 at 21 06 01](https://user-images.githubusercontent.com/2427214/36692652-f710fc18-1b38-11e8-93c7-c18534879a61.png)

javascript:

```
        const annotations = [
            {
              className: "dot-com-bubble",
              type: "bounds",
              bounds: [{ dt: moment(this.props.date).startOf('day').add(4,'h')},{ dt:moment(this.props.date).startOf('day').add(14,'h') }],
            }
        ];

```

And in the css:

```
.dot-com-bubble .subject{
  fill:lightgreen;
  stroke:lightgreen;
  fill-opacity:0.5;
}

.dot-com-bubble .connector{
  display:none;
}

```
If there is a way to remove the connector in javascript I would prefer that.

**Comment by emeeks** [comment]
Yes the annotations follow the `react-annotation` spec so you can send your annotation react-annotation style instructions for how to render. In the case of removing the connector that's easy, there's a `disabled` property of annotations that takes an array:
```
        const annotations = [
            {
              className: "dot-com-bubble",
              type: "bounds",
              disabled: ["connector"],
              bounds: [{ dt: moment(this.props.date).startOf('day').add(4,'h')},{ dt:moment(this.props.date).startOf('day').add(14,'h') }],
            }
        ];
```

**Comment by jhvanderven** [comment]
Thanks
