### ISSUE TITLE
y1 option for lineType "line"

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#16]
Add support for "line" you have y1, an accessor function that lets you draw the bottom/top of a line so that a user can send something like:

`{ type: "line", y1: () => 0 }` to create zero-bottom lines or:
`{ type: "line", y1: d => d.value + 5 }` to create ribbon-like lines.

**Comment by emeeks** [comment]
Added in 1.0.6 but needs documentation so leaving this open until I add it to the API docs.

**Comment by bstaats** [comment]
Either this is not working as intended or I'm using this for the wrong use case. I am trying to produce a line chart with the area underneath filled in.

Here are the line props to XYFrame:
```
lineProps: {
          size: [100, 60],
          lineType: { type: 'line', y1: () => 0, interpolator: curveBasis },
          lineStyle: { stroke: color, fill: color },
          lines: [data],
          xAccessor: (l, i) => i,
          yAccessor: l => l,
        }
```

Data is in the format: `[0.1, 0.2, 0.8, 0.4, 0.3, ...]`

Here is the error I get:
```
lineDrawing.js:212 Uncaught TypeError: Cannot assign to read only property 'yBottom' of object '#<Object>'
    at lineDrawing.js:212
    at Array.forEach (<anonymous>)
    at lineDrawing.js:211
    at Array.forEach (<anonymous>)
    at Object.lineChart [as line] (lineDrawing.js:210)
    at dataFunctions.js:254
    at calculateDataExtent (dataFunctions.js:119)
    at ProxyComponent.calculateXYFrame (XYFrame.js:254)
    at ProxyComponent.wrappedMethod (react-hot-loader.development.js:502)
    at ProxyComponent.componentWillMount (XYFrame.js:154)
```

**Comment by emeeks** [comment]
Looks like you're using it the right way, I'll take a look.

**Comment by bstaats** [comment]
I figured out the issue. The code is fine. The problem came from the data objects I was feeding it were Immutable. See #188. I unwrapped my objects `lineProps.lines.map(l => l.asMutable())` and it works fine.

**Comment by emeeks** [comment]
Glad to hear. I took a look and couldn't reproduce it and thought I had posted that here but apparently not... Closing this.
