### ISSUE TITLE
ORFrame Frame Hover Tooltip issues

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#160]
I'm trying to make a timeline graph using Semiotic, and there is a problem with the tooltips on the frame hover that I can't work around. The tooltips seem almost arbitrary as to when it switches from one to the next. For example, in the timeline graph, when the mouse is on x drawn on the Grover Cleveland datapoint, it show's Harrison's tooltip.
So, the overarching issue is that I'd like the frame hover tooltip type (pieceHoverAnnotation) to show datapoints of the content you are actually hovering over.
![image](https://user-images.githubusercontent.com/19843782/36752864-fc3a90fa-1bc9-11e8-97a4-59e692fbd7c4.png)
I've noticed that with hoverAnnotation and pieceHoverAnnotation disabled, the customHoverBehavior and customClickBehavior work exactly how I'd like them to (it only counts as hovering/clicking the piece if the mouse is actually over the piece). The only problem with the customHoverBehavior is that I don't know how to make the tooltipContent show up using it.

**Comment by emeeks** [comment]
I'd early on thought to try to use voronoi overlays with bar charts, relying on some center point of the bar. In 1.18, which will be coming soon, this will be replaced with an overlay that corresponds to the shape of the bar/timeline. Sorry for the inconvenience.

**Comment by emeeks** [comment]
Fixed with 1.8.1. Now all hover for timelines, bar charts and cluster bar charts is based on the shape itself and not some weird region.
