### ISSUE TITLE
Twisting Ribbon in Sankey

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#163]
It looks like the source/target coordinates of the arcs are reversed sometimes-- both in your example and in mine.  This wasn't an issue until I updated to a more recent version (last week? sorry, I don't quite remember when).

<img width="898" alt="screen shot 2018-02-28 at 1 56 12 pm" src="https://user-images.githubusercontent.com/12260067/36806956-ac5c755a-1c8f-11e8-93fe-c0ad50e76325.png">
<img width="1259" alt="screen shot 2018-02-28 at 1 56 35 pm" src="https://user-images.githubusercontent.com/12260067/36806955-ac48d9a0-1c8f-11e8-8240-89f16f4a9084.png">

**Comment by emeeks** [comment]
Oh. Good.

**Comment by emeeks** [comment]
Found the problem, will be fixed in 1.8
