### ISSUE TITLE
Responsive Frames trap keyboard focus

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#164]
When someone uses the keyboard to navigate a page, they should be able to tab through elements without focus being trapped in any element.  The responsive ordinal and xy frames both trap the user, even with tabIndex set to -1 on the div immediately surrounding the responsive frame.  A potential fix: when tabIndex="-1" is added to the object.resize-sensor element, keyboard navigation resumes expected functionality.

This can be recreated by turning on voiceover (cmd + f5 on a Mac) and tabbing through a page containing a responsive frame.

Thanks :)

**Comment by emeeks** [comment]
`element-resize-event` doesn't give any way to inject attributes into the generated object so I forked it and made a version that is generating an Object with tabIndex="-1". However, I'm still not great at testing this out so if you have a chance, could you build and check that this is enough of a solution?

**Comment by emeeks** [comment]
This is in 1.8.2 if you want to test it out.

**Comment by mmazanec22** [comment]
Works beautifully!  Thank you.
