### ISSUE TITLE
ResponsiveOrdinalFrame responsiveHeight doesn't work

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#165]
Setting responsiveHeight={true} on the ResponsiveOrdinalFrame does nothing or just breaks. For example, if you add responsiveHeight={true} to https://codepen.io/emeeks/pen/PQpRdR, the page just fails to load. On the visualizations I'm working with, it loads, but it doesn't respond to the height changing at all and often just ignores the size of it's parent element but only for the height. The width scales beautifully.

**Comment by emeeks** [comment]
Make sure that the parent container is getting its height properly via the DOM, that seems to be the major pain point with `height` which doesn't follow the same box model rules as `width`. I tested it and it seems fine:

![untitled](https://user-images.githubusercontent.com/495634/36878347-6c3f66b4-1d73-11e8-9fe2-4bcd5d562418.gif)

I'll take a look at the codepen example and see if I can update it to reflect the right settings.

**Comment by ZachHaber** [comment]
Hmm, I think the problem might be that the parent containers height can't be set as a percentage.

**Comment by emeeks** [comment]
I updated the codepen to have the body, html and div#main all have 100% height and it seems to work fine: https://codepen.io/emeeks/pen/PQpRdR

Gonna close this but if you still have issues, feel free to re-open or just comment.
