### ISSUE TITLE
Enhancement: Radial OrdinalFrame Labels on the outside

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#166]
Something I'd like to be able to do is have the oLabels be able to be displayed neatly around the outside of the graph akin to this:
![image](https://user-images.githubusercontent.com/19843782/36877824-bb0d041e-1d81-11e8-9416-0170cf75d0df.png)
This would be most helpful when working with datasets that have long names for the different categories or pie charts with some very small sections.
Thank you for all of your hard work on this library!

**Comment by emeeks** [comment]
You're right that should be an option via some kind of property or offset or something.
