### ISSUE TITLE
Almost all of your Semiotic code-pens appear to be broken

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#167]
I was checking the #165 on my work laptop to try and fix things, and I noticed that the https://codepen.io/emeeks/pen/PQpRdR page wasn't working. I checked just now, and it looks like most of them aren't working.
The error being give on the browser's console is: "React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in."

**Comment by emeeks** [comment]
Yeah I saw this, sorry for the hassle, working on it now.

**Comment by emeeks** [comment]
FYI you can move the examples back to 1.7.14, that's the last version that was working. Will let you know when I get a working 1.8.x version up.

**Comment by emeeks** [comment]
1.8.3 fixes this.
