### ISSUE TITLE
Feature request - Array arguments on axis.tickFormat

### ISSUE THREAD

**Issue by jeff3dx** [emeeks/semiotic#170]
Please consider adding enumeration arguments to **axis.tickFormat**. The function would be **(value, index, array)** just like Array.map or Array.filter. This is useful for x-axis date time ticks. I often want to change the tick format based on the sequence.  For instance the first tick shows complete day/month h:m but remaining ticks just h:m. Or include day number on each tick immediately following a midnight changeover, etc. This requires having the tick sequence available when formatting one tick.

**Comment by emeeks** [comment]
This will be available in the next release

**Comment by emeeks** [comment]
In 1.9.0
