### ISSUE TITLE
DividedLine won't render

### ISSUE THREAD

**Issue by infograafikko** [emeeks/semiotic#171]
I can't get DividedLine to render. You can see an example in Codepen: https://codepen.io/Sokrates86/pen/yKBQeV

It seems that svg path has values but it doesn't render correctly. Also is it possible to make ResponsiveDividedLine without SVG tags?

**Comment by susielu** [comment]
Thanks for providing an example. The line is rendering it's just wayyyyy off screen. You'll need to create some scales to remap the data into screen coordinates. Right now you're just mapping the values directly to pixel values:

![image](https://user-images.githubusercontent.com/1449837/37180605-80c5809e-22de-11e8-890a-81e03684243c.png)

**Comment by emeeks** [comment]
Susie is right, here's a version with scales:
https://codepen.io/emeeks/pen/NYWwJR

**Comment by infograafikko** [comment]
Thank you so much!
