### ISSUE TITLE
Immutable data support

### ISSUE THREAD

**Issue by mkascel** [emeeks/semiotic#188]
• Currently it looks like this lib doesn't support immutable data sources (passed via `lines` etc).  This stumped me for a while as there are just exceptions thrown that indicate something is wrong with the data but as a newcomer, it wasn't clear that this wasn't simply a usage/API issue.  Is this by design and if so, should we add something to the docs regarding this?  I am using seamless-immutable.

**Comment by emeeks** [comment]
@mkascel There is no built-in immutable support are you sending immutable lists or are you sending `toArray()` results? It wouldn't know what to do with the native immutable data types but if there's something about the way that it's formatting array outputs that I can account for, I'd be happy to take a look. I don't plan to deal with immutable anytime soon, though I would be happy to support someone if they wanted to work on that, so if you can think of where to place that in the docs just let me know.

**Comment by mkascel** [comment]
I think immutability would be a nice feature to have, even in fairly complex React apps there isn't a need to unwrap immutable data structures, D3 is one good example that is pertinent especially to this project.  But yes currently what I am doing is unwrapping (seamless uses `.asMutable()` vs Immutable.js' `.toJS()`.

I think (first naive assumptions anyway) supporting immutable structures could be relatively trivial.  From what I can tell by the stacktraces (I haven't dived very deep into your source), you are directly accessing/manipulating the passed in data, vs making a copy of the data passed and then working with that internally in your library.

For instance, something like this pseudo-code could work at the top-level of where you ingest the data source:

```
const unwrappedContainer = [...dataSource];
const unwrappedData = unwrappedContainer.map(obj => Object.assign({}, obj));
```

This copies over the values without the immutability, at least it seems on my end.  Something more robust might need to be done regarding data structure type-checking etc.

Is there some central top-level place you ingest the data where it would be best to do something like this?

**Comment by mkascel** [comment]
Alternatively, these libs have built in methods to detect whether something is immutable [like this for seamless](https://github.com/rtfeldman/seamless-immutable#isimmutable), which you could then unwrap with the built-in method, but then you would need to support current/future immutability libs.

**Comment by emeeks** [comment]
I think there are top-level moments when I should be able to unroll immutable structures. I expect it would only be for the data and nothing else, right?

**Comment by emeeks** [comment]
I don't think I'll be doing anything to add immutable support to Semiotic so I'm going to close this.
