### ISSUE TITLE
Tooltip Overlapping

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#191]
I'm using the React Grid Layout module for a reordering grid. I found out that if I change the order of the graphs using this library, by moving a graph down, that the tooltips will start showing up underneath the graph above it. I believe this is occurring because the grid library uses transformations to accomplish its task rather than reordering the graphs in the DOM. Here's a codepen that demonstrates the problem: https://codepen.io/anon/pen/WzajER
![image](https://user-images.githubusercontent.com/19843782/38437165-37a813c0-399c-11e8-88e3-22d09d1ad6fe.png)

I couldn't find a way to fix this directly, instead opting to forcibly change the rendering order which isn't the most optimal solution to this. So, my question to you is if you know any way to fix this since it is outside my current knowledge. Thank you for all of your hard work on this library!

**Comment by emeeks** [comment]
What an odd issue. Changing the z-index doesn't do anything. I'll try to dig into it more and let you know what I find. If you see anything, please post.

**Comment by ZachHaber** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Positioning/Understanding_z_index/The_stacking_context
I think it is because of stacking contexts. Since visualization layer of one graph is in a different stacking context than the visualization layer of the other graph, the z-index won't make any difference at all. The only way to do it would be to change the z-index of the ancestor element (in this case, the react-grid-layout item), but that makes it still have the same problem due to having to set them to equal z-indexes in order to not have the problem reversed.

**Comment by ZachHaber** [comment]
https://codepen.io/anon/pen/LdqaRJ
I came up with a way to fix it on my/the grid layout's end by changing the z-indices with the layout order changes. As far as I'm aware, I don't think there is any way for part of a component to escape it's stacking context.
So, unless you have any thoughts as to how to solve this from semiotic's end, I think this issue can be closed. Thanks for your time!

**Comment by emeeks** [comment]
Thanks for muddling through it, Zach. I wish there was a better way to handle it but I will close this one.
