### ISSUE TITLE
XY Graph Marks fall off the graph when the data is all the same

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#197]
I have an XY graph where all the data is the same and it displays pretty badly. If its possible, I'd like to be able to have graphs like these where there isn't any variation and the yExtent is unset ([undefined,undefined]) for the marks to remain in the center of the graph. I tried setting the yExtent to [0,undefined], but that just moved the points all to the top of the graph.
![image](https://user-images.githubusercontent.com/19843782/38756626-c87db718-3f2f-11e8-897e-3f8c542d17f5.png)
Edit: As a note, this is rather low priority for me.

**Comment by emeeks** [comment]
I'm not sure I consider this a bug. I can't calculate some kind of padding if there's not variation among the dataset, but you can and you can set the extent as such (with positive or negative values). Consider using `swarm` or `point` in `OrdinalFrame` if you don't have a y dimension.

But maybe I don't understand what you're doing, so feel free to post the data and I'll reevaluate.
