### ISSUE TITLE
Weird transition when changing the data prop

### ISSUE THREAD

**Issue by mdutra** [emeeks/semiotic#219]
I get a weird transition when I change the data of the stacked bar chart. The bar moves below the bottom border and then it moves back up. The same doesn't happen with the horizontal projection.

You can see here on codepen clicking on "Filter" and "Restore":
https://codepen.io/mdutra/pen/vjeJbN?editors=0010

Is there a way to manipulate the transition or an option to turn it off?

**Comment by emeeks** [comment]
I noticed this weird animation when I was demoing, I'm going to dig it out. As far as methods turning off animated transitions you can do a few things:

`renderKey` is a property of the frame and if you send it a function it will ensure that the same object will be rendered in transitions (by default the key is array position, which can cause weirdness) so if you can send it some kind of unique identifier for each datapoint that will cause more fluid transitions when adding or filtering.

`baseMarkProps` is a property of the frame which sends properties to all marks generated by the frame. If you send it:
```
baseMarkProps={{ forceUpdate: true }}
```
That will stop all animation entirely.

**Comment by emeeks** [comment]
I'll close this when I can resolve the funky default animations, which shouldn't be so janky.

**Comment by niwsa** [comment]
I am facing some issue with animations where the points freeze and then fall into place after some time.But the issue occurs sporadically.Below is a screenshot when it happened.This happens when new lines are set via props.
![points_freeze](https://user-images.githubusercontent.com/3107922/55976691-9d9cb780-5caa-11e9-808c-85dd88b2eb21.png)
