### ISSUE TITLE
missing file extension for scripts after cra eject

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#223]
will send a PR to fix this

https://github.com/emeeks/semiotic/blob/6a7c913dcd974dd2038d61bfd3500c13e198d40f/scripts-bak/docs

#### history
Semiotic devs in the past wrote useful scripts and placed them in the `scripts` directory 

#### problem 
create-react-app `rm -rf`'s (deletes) and then re-creates the `scripts` directory during the eject process.  this would delete the dev-created Semiotic scripts that we want to keep

#### short-term solution 
rename scripts directory `scripts-bak` to preserve the Semiotic dev-created during eject process. this occurred in https://github.com/emeeks/semiotic/pull/212

#### long-term solution
now, after cra eject, move the contents of `scripts-bak` back to `scripts` and add missing `.sh` file extension to shell scripts

**Comment by emeeks** [comment]
You're the best @micahstubbs

**Comment by micahstubbs** [comment]
🙌
