### ISSUE TITLE
Customized hoverAnnotation

### ISSUE THREAD

**Issue by colinmcd94** [emeeks/semiotic#225]
I'm trying to figure out if/how you customized the annotation in the Line Chart documentation, specifically in this image: 

<img width="838" alt="screen shot 2018-05-10 at 12 42 01 pm" src="https://user-images.githubusercontent.com/3084745/39881854-2051b50e-5450-11e8-8545-768323b3949f.png">

The annotation contains the title of the movie, and styles the point values with prefixes ("Week " and "$"). The code snippet below this graph doesn't seem to indicate how this was done...am I missing something?

**Comment by emeeks** [comment]
Oh you're right I didn't update the code docs. Sorry about that! Here's the code running that:
```
<XYFrame
            title={"Two Movies"}
            size={[700, 400]}
            dataVersion="fixed"
            lines={movies}
            xAccessor={"week"}
            yAccessor={"grossWeekly"}
            lineStyle={{ stroke: "#00a2ce" }}
            lineType={{ type: "line", interpolator: curveCardinal }}
            showLinePoints={true}
            pointStyle={() => {
              return { fill: "#00a2ce" }
            }}
            hoverAnnotation={true}
            tooltipContent={d => {
              return (
                <div className="tooltip-content">
                  <p>{d.parentLine.title}</p>
                  <p>Week {d.week}</p>
                  <p>${d.grossWeekly}</p>
                </div>
              )
            }}
            margin={{ left: 80, bottom: 50, right: 10, top: 40 }}
            axes={[
              {
                orient: "left"
              },
              {
                orient: "bottom"
              }
            ]}
          />
```

**Comment by emeeks** [comment]
It's the `tooltipContent` where that's happening.

**Comment by colinmcd94** [comment]
Works like a charm!
