### ISSUE TITLE
mappong --> mapping

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#226]
docs https://emeeks.github.io/semiotic/#/semiotic/creatingbarchart

![screen shot 2018-05-12 at 2 19 34 pm](https://user-images.githubusercontent.com/2119400/39961638-874ebe28-55ef-11e8-9676-f54a97dfb117.png)

**Comment by emeeks** [comment]
Mappong was an important mapping game in the early 80s on the Atari and I won't have you impugn it.

**Comment by micahstubbs** [comment]
😂 🕹
