### ISSUE TITLE
nice error messages accessor props

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#228]
so I want to draw a bar chart.  fresh off my success drawing a line chart with `XYFrame`, I copy my line chart props and change some things to match the bar chart example that I see here 

https://emeeks.github.io/semiotic/#/semiotic/creatingbarchart

so I have

```jsx
<OrdinalFrame
            size={[300, 500]}
            data={barChartData}
            xAccessor={"user"}
            yAccessor={"tweets"}
            style={{ fill: "#00a2ce", stroke: "white" }}
            type={"bar"}
            oLabel={true}
          />
```

while the example has

```jsx
<OrdinalFrame
            size={[300, 500]}
            data={barChartData}
            oAccessor={"user"}
            rAccessor={"tweets"}
            style={{ fill: "#00a2ce", stroke: "white" }}
            type={"bar"}
            oLabel={true}
          />
```

at first, I couldn't spot the difference.  when I went back and read the text above the example again, I realized "oh! we're talking about `ordinal` things and `ranges` now" 💡  

it would be nice to add a "Did you mean...?" error message that would appear in the browser console when a user passes a commonly-used wrong prop type.

for example 

> Whoa there, did you mean `oAccessor`?  You passed the prop `xAccessor` to component `OrdinalFrame`,  but it does not accept a prop with this name.  read more at https://emeeks.github.io/semiotic/#/semiotic/creatingbarchart

![screen shot 2018-05-12 at 2 49 56 pm](https://user-images.githubusercontent.com/2119400/39961850-cc2047f2-55f3-11e8-8414-f833694663c3.png)

**Comment by micahstubbs** [comment]
inspired by this conversation in the slack channel

![screen shot 2018-05-12 at 2 49 02 pm](https://user-images.githubusercontent.com/2119400/39961844-ad9c8412-55f3-11e8-9205-2c8b7a96dd0d.png)


https://d3js.slack.com/archives/C6Z682WBH/p1526101098000032

**Comment by emeeks** [comment]
That's a very good idea but I'm not sure how technically to do that short of a crude `console.error` if a Frame is sent a prop that another frame has. I could see that working, though. We take all the prop-types and set them up as arrays in a separate resource and then test them when a component is mounted (does it need to happen more than this?) and then we could either say generically something like `hey you passed xAccessor but that's an XYFrame prop, this is an OrdinalFrame did you mean to do that?` or we could write specific info for specific props but that seems challenging to maintain.

I'll get started on the system I described here but if you can think of some way to go about the other, let me know. Also should it happen more than `componentDidMount`? I dislike the idea of checking it at every new prop.

**Comment by micahstubbs** [comment]
I imagine that checking once in the beginning at `componentDidMount` should do it, for the dev use cause that I had in mind.

will give this more thought for other approaches.  the approach you describe does sound reasonable to me.

**Comment by emeeks** [comment]
In 1.10.4 you'll get a console error telling you if a prop you send to a Frame isn't applicable which will also tell you if it's valid for another frame.
