### ISSUE TITLE
high level barWidth (markWidth) prop for OrdinalFrame

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#229]
had this idea for an enhancement that would improve dev experience.

I'd like to have a prop for `OrdinalFrame` called `barWidth` or `markWidth` that would set the effective value of the short dimension of the bar (literally width or height depending on the orientation of the chart).  

We can think of this prop as a convenience wrapper for `pixelColumnWidth` that subtracts the `oPadding`, if any.

I imagine this prop being used by `OrdinalFrame` to set pixelColumnWidth if it is unspecified, like this:

```javascript
pixelColumnWidth = barWidth - oPadding
```

**Comment by micahstubbs** [comment]
related conversation from the `d3js/semiotic` slack.  note that this idea of `barHeight` I mention is the same thing as `barWidth`. maybe we need a better orientation independent name for this new prop? 🤔 
 
![screen shot 2018-05-14 at 1 45 57 pm](https://user-images.githubusercontent.com/2119400/40022747-be8c7648-577d-11e8-98ed-b759d113990d.png)

**Comment by emeeks** [comment]
So in this case you would set `oPadding` and `barWidth` and I would calculate the total `pixelColumnWidth` as the one plus the other? Pretty simple.

That said, you're right about terminology. I used "column" together with width hoping that in horizontal projection it still made sense. Ordinal is hopelessly abstract for users, "category" is where I'd go for the frame name if a Semiotic 2 happened but that still doesn't sound good paired with "width" or anything else.

Naming is the second hardest problem in programming. The first hardest is smoosh optimization with idempotent functional linear algebra organic chemistry fuzzy math frequentist statistics.

**Comment by micahstubbs** [comment]
1) yes that's what I had in mind

2a) names are hard, right.  my opinion is that the new ordinal axis name abstraction is worth keeping, and just needs docs + education.  it's react-land after all, people here seem to love new abstractions.  

2b) for marks what can vary orientation, absent obvious naming conventions from outside to adopt, I'd say that ideas of `length` and `width` make sense, where length is the size of the _longer_ edge and width is the size of the _narrower_.  

2c) if Semiotic is consistent about how it calls these inner chart element dimensions, users should be able to make sense of it.  so I like the idea of picking reasonable names and using them consistently across different frames.

**Comment by emeeks** [comment]
I decided not to implement this. Rather than add more syntactic sugar I figure this is achievable with just the existing `oPadding` & `pixelColumnWidth`.

**Comment by micahstubbs** [comment]
@emeeks fair enough.  is there a public example of doing this with the existing `oPadding` & `pixelColumnWidth`?

might try to create & contribute one if not.
