### ISSUE TITLE
Download Doesn't Get Data Accessors

### ISSUE THREAD

**Issue by mph006** [emeeks/semiotic#23]
The download feature in the XYFrame doesn't receive x/yAccessors.

Looks like they aren't being passed to `xyDownloadMapping` as expected
https://github.com/emeeks/semiotic/blob/master/src/components/downloadDataMapping.js#L10

Example:
```
<XYFrame
          {...sharedProps}
          className="line-xy"
          lineStyle={(d) => {return {stroke:d.color, strokeWidth: '2.5px'}}}
          lines={this.formatData(this.props.data)
            .filter((d)=>{return this.state.filterIndex.indexOf(d.id) === -1})}
          axes={axes}
          lineDataAccessor={(d)=> d.data}
          xAccessor={(d) => d.date}
          yAccessor={(d) => d.count}
          //lineRenderMode={"sketchy"}
          hoverAnnotation={true}
          download={true}
          //defined={(d) => d !== null}
          tooltipContent={(d) => {
            return this.fetchTooltipContent(d);
          }}
/>
```

<img width="438" alt="screen shot 2017-09-08 at 3 49 28 pm" src="https://user-images.githubusercontent.com/3487290/30234040-a45ec1a0-94ae-11e7-9da1-2112be1f5eaf.png">

I suspect this is an issue in the OR frame as well.

Similarly, is there a way to pass a data accessor to`networkNodeDownloadMapping` / `networkEdgeDownloadMapping`?

**Comment by emeeks** [comment]
Frames need to also be passed `downloadFields` which is an array of field ids to download the data for. As of 1.0.6 there is also support for `download={points}` in XYFrame to download the underlying points of lines and areas.
