### ISSUE TITLE
Keyboard controlled tooltip should disappear on blur

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#234]
When a user moves focus away from a visualization, the corresponding tooltip should disappear.

<img width="1235" alt="screen shot showing tooltips on a diverging line/bar chart" src="https://user-images.githubusercontent.com/12260067/40062479-53cbebde-5829-11e8-9538-f20e89ecb6ab.png">

**Comment by emeeks** [comment]
Will be in the next release.

**Comment by emeeks** [comment]
Fixed in 1.10.4

**Comment by rkz2021** [comment]
I'm trying to integrate a tooltip where the content is editable. Followed the sample provided here -  https://codepen.io/emeeks/pen/GdOGZZ?editors=0110. How did you fix the tooltip disappear issue? Please help.
