### ISSUE TITLE
Pattern with background color

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#235]
I have a ordinal component with a fill color that is set based on the data. I want to be able to add in a pattern to the component that works with the already existing background color (without having to define a pattern for each different fill color). Is that possible?
I tried adding a piece-class to use css to make the pattern, but that didn't show at all. Thanks for your help!

**Comment by emeeks** [comment]
It's hard for me to exactly tell what you want to do. CSS patterns and SVG patterns don't mix but I've got some docs on how to use SVG patterns with Semiotic:
https://emeeks.github.io/semiotic/#/semiotic/usingpatterns

Could you take a look and let me know where your use case doesn't match up and I'll be happy to help you work through it.

**Comment by ZachHaber** [comment]
For example, I have an array that goes to a list of colors: ['red','blue','white','pink']. I had it set up so that the fill was style.fill={d=>colors[d.accessor1]}.
Now, I have a reason to set up a pattern on some of the data based on accessor2, but I still need the background colors to be based on accessor1.
I'm using the PatternLines from @vx/pattern. The issue is that due to how the svg is processed I can't give a background color dynamically. As the usual place to do that (e.g. style.fill) is used to set up the pattern. I can give the pattern itself a background, but that is more or less a static color. I can't modify that using accessor1.
I've tried using currentColor to fix the issue, but due to the use(#pattern), the currentColor property doesn't actually apply to the pattern that's in the defines. It goes through the pattern's actual html hierarchy for the currentColor instead of the mark's.
The only thing I could do to fix it was to define the pattern for each pattern/color combination and use the pattern for that combination in the fill function.

**Comment by emeeks** [comment]
The only way I know to accomplish this is exactly what you describe: to pre-generate the patterns. I could imagine a partner library for libraries like Semiotic that somehow abstracts this process but I can't really see an efficient way to build this out. I'm going to close this but feel free to reopen or comment if you think you see a good way to address it.
