### ISSUE TITLE
Duplicate documentation in chart subtitles

### ISSUE THREAD

**Issue by koltclassic** [emeeks/semiotic#237]
It looks like parts of the documentation for Creating a Bar Chart are duplicated by Creating a Pie Chart and Creating XY Plots. I can submit a PR for this if you'd like, but I didn't want to assume anything about how you'd like these charts to be defined and explained. Thank you for the framework!

### Creating a Bar Chart
<img width="836" alt="screen shot 2018-05-18 at 8 48 46 am" src="https://user-images.githubusercontent.com/6091219/40235504-84309d3c-5a78-11e8-94ad-a4e48420f60e.png">

### Creating a Pie Chart
<img width="807" alt="screen shot 2018-05-18 at 8 48 50 am" src="https://user-images.githubusercontent.com/6091219/40235509-87d13ef6-5a78-11e8-9432-ab32c02fc1d3.png">

### Creating XY Plots
<img width="765" alt="screen shot 2018-05-18 at 8 47 30 am" src="https://user-images.githubusercontent.com/6091219/40235521-8e8d0914-5a78-11e8-9992-00a4e3f29b0b.png">

**Comment by emeeks** [comment]
Ha, yes, feel free to file a PR or I will clean this up today.

**Comment by emeeks** [comment]
Fix pushed and will be active when I update the docs next
