### ISSUE TITLE
XYFrame Realtime Lines -  Error: <xxx> attribute xxx: Expected length, "NaN".

### ISSUE THREAD

**Issue by koltclassic** [emeeks/semiotic#238]
While using the XYFrame Realtime Lines example, when hovering over the chart occasionally two concurrent errors will be logged.
 The only two errors I have seen are:
`Error: <text> attribute y: Expected length, "NaN".`
`Error: <circle> attribute cy: Expected length, "NaN".`
 I've included a screenshot of these errors below. I am on Chrome 66.

<img width="1139" alt="screen shot 2018-05-18 at 9 17 53 am" src="https://user-images.githubusercontent.com/6091219/40237329-2a194078-5a7e-11e8-8e21-9795e75c192c.png">

**Comment by emeeks** [comment]
Will take a look. This example has always been a bit sketchy not because of the Semiotic bits but because of the hacky way I simulate a stream of data.

**Comment by emeeks** [comment]
Found it--the problem happened when the returned relative position is zero and that was failing one of those great JavaScript falsy tests. Will be fixed in the next release.

**Comment by koltclassic** [comment]
Awesome, great catch!

**Comment by emeeks** [comment]
Resolved in 1.11.1
