### ISSUE TITLE
projection="radial" with settable origin angle?

### ISSUE THREAD

**Issue by cvkline** [emeeks/semiotic#240]
I've fairly easily gotten a donut chart rendered.  But our product designer long ago standardized on donut charts with an origin at "six o'clock" and moving clockwise around from there. I can't figure out any easy ways to rotate the radial origin to something other than the SVG zero position, which is at twelve o'clock.

Am I missing something in the prop documentation, or is there some hack I can leverage?  If not, I'd like to make a feature request for such a thing. If it comes down to a feature, I'll volunteer to write it.

**Comment by emeeks** [comment]
Interesting. I'll add an `angleOffset` to the type property so can send something like: `type={{ type: "bar", angleOffset: 180 }}` to change the origin angle.

**Comment by cvkline** [comment]
Awesome, thanks!  If I may make a suggestion, that could be generalized to `angleRange: [ start, end ]` and then it'd be really easy to make "speedometer" type charts such as the attached, which is a bespoke viz I currently have in pure d3.  I guess that might get a little hairy if I wanted a full circle starting at 6-oclock, though;  `angleRange: [ 180, 180 ]` might be difficult to interpret.

<img width="433" alt="screen shot 2018-05-19 at 4 34 23 pm" src="https://user-images.githubusercontent.com/6576592/40273256-9c506900-5b82-11e8-897b-a9643d1362ca.png">

**Comment by emeeks** [comment]
Implemented in 1.10.5
