### ISSUE TITLE
responsiveHeight is not a valid OrdinalFrame/XYFrame prop

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#241]
Since I updated to the latest version, I've been getting error messages saying that responsiveHeight is not a valid prop for both Ordinal and XY frames. I'm using the responsive frames, and the responsiveHeight is working, I think the prop is being incorrectly passed on from the responsive variant which consumes it to the normal frame which doesn't see it as a valid prop.

**Comment by emeeks** [comment]
You're right, it shouldn't be passed down. It won't cause any issues but I'll make sure to fix it in the next release.

**Comment by ZachHaber** [comment]
Fixed in 1.10.5, thank you Elijah!
