### ISSUE TITLE
Diverging bar hover keys are the same, prompting warning

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#242]
Diverging bar chart warning message: "Warning: Encountered two children with the same key, `hover-Tue Aug 01 2017 00:00:00 GMT-0400 (EDT)`. Keys should be unique so that components maintain their identity across updates. Non-unique keys may cause children to be duplicated and/or omitted — the behavior is unsupported and could change in a future version."

**Comment by emeeks** [comment]
Resolved in 1.11.5
