### ISSUE TITLE
Radial bar charts don't render in IE11

### ISSUE THREAD

**Issue by cvkline** [emeeks/semiotic#249]
I'm creating a donut chart in Semiotic with this call:

`        <OrdinalFrame
          size={[this.state.vizWidth, this.state.vizHeight]}
          data={data}
          oAccessor="category"
          dynamicColumnWidth="value"
          rAccessor={constant(1)}
          renderKey={d => d.category}
          type={{
            type: 'bar',
            innerRadius: this.state.vizWidth / 2 - donutThickness,
            offsetAngle: 180,
          }}
          projection="radial"
          style={d => ({ fill: colors[d.category], stroke: 'white' })}
          foregroundGraphics={this.foreground()}
          margin={margin}
        />`

It works fine but in IE11, the donut chart elements don't render. The foregroundGraphics do. Inspecting the DOM shows that there's an empty React component rendered where the data-visualization `<g>` would go.

Attaching the visual and the part of the DOM tree.

![screen shot 2018-05-29 at 5 13 04 pm](https://user-images.githubusercontent.com/6576592/40689323-4c357784-6367-11e8-9f7d-851ef8e541b3.png)
![screen shot 2018-05-29 at 5 12 09 pm](https://user-images.githubusercontent.com/6576592/40689324-4c4710de-6367-11e8-9f68-e660ee196add.png)

**Comment by emeeks** [comment]
@cvkline Could you tell me your environment (React version, polyfills) and give me the settings of the OrdinalFrame you're using?

**Comment by cvkline** [comment]
The exact OrdinalFrame call is above; did you need more?

    "react": "15.6.2",
    "react-dom": "15.6.2",

And we load this as a part of our main app HTML:

<script src="https://cdn.polyfill.io/v2/polyfill.min.js?features=default,Intl.~locale.en,Array.prototype.findIndex,Array.prototype.includes,Array.prototype.find,HTMLCanvasElement.prototype.toBlob,Object.assign"></script>

**Comment by emeeks** [comment]
No you're right I looked right past that, sorry. But I can't seem to reproduce this on IE11 using BrowserStock:

<img width="519" alt="screen shot 2018-05-30 at 12 36 52 pm" src="https://user-images.githubusercontent.com/495634/40743388-367ebe56-6406-11e8-84b2-186e3a504ee6.png">

Can you check to make sure something IE11-wise isn't modifying the data you're sending to the frame? And if you could give me the actual settings (size, foregroundGraphics, data formatted, accessors) I think I'll need them to keep testing around with this.

**Comment by cvkline** [comment]
Sure, the data is just  `[ { category: 'completed', value: this.props.completed }, { category: 'incomplete', value: this.props.total - this.props.completed } ]`

`constant(1)` is just from lodash and represents a function that always returns 1.

size is computed but 300x300 is about right.

foregroundGraphics is as follows. The `goodData` function just makes sure the values in the props are present and nonzero. `format` is just d3.format.

  // Returns JSX for the central annotation
  foreground() {
    if (this.goodData(this.props.values)) {
      const { completed, total } = this.props.values;
      const pctComplete = completed / total;
      const pctFormat = format('.0%');
      const numFormat = format(',.0f');

      return [
        <text className="percent-complete" dy="-24px">
          {pctFormat(pctComplete)}
        </text>,
        <text className="complete">
          {I18n.t('%{completed} out of %{total}',
            { completed: numFormat(completed), total: numFormat(total) }
          )}
        </text>,
        <text className="complete bold" dy="22px">
          {I18n.t('Enrollments Complete')}
        </text>,
      ];
    }
    else {
      return [<text className="no-data" dy="8">{I18n.t('No data')}</text>]
    }
  }

**Comment by cvkline** [comment]
If it is any help to you at all, I've managed to contrive a small example donut chart that behaves in IE11 exactly like our application does:  the `<OrdinalFrame>` renders but the actual visualization layer is an empty React component. See `http://www.overcautio.us/~kline/Semiotic-IE11/index.html`  There's nothing fancy here, just a webpack-built app that brings in React, Semiotic, and also hits up `polyfill.io` to fix up all the native JS methods that IE11 doesn't implement.

Happy to share the code itself if it'll help.

**Comment by emeeks** [comment]
Fixed (finally) in 1.11.13
