### ISSUE TITLE
prop to set tooltip for axis tick labels

### ISSUE THREAD

**Issue by micahstubbs** [emeeks/semiotic#255]
curious, is there a semiotic-native way to add a tooltip to ordinal axis tick labels?  I've truncated the text I pass into semiotic, and now I want to show a tooltip with the full text for the truncated labels.

something like this `onMouseOver` synthetic event handler in this pseudocode example?

```javascript
          oLabel={(d, i) => (
            <text
              style={{ textAnchor: 'end' }}
              y={4}
              onMouseOver={() => console.log('axis tick label tooltip')}
            >
              {truncateString(d, 15)}
            </text>
          )}
```

**Comment by emeeks** [comment]
Well, technically since you can send JSX, you should be able to register a `onMouseEnter` and `onMouseLeave` or `onClick` or any other events you want on them. I've never done it but there shouldn't be anything that stops you.

**Comment by emeeks** [comment]
I'm not sure `onMouseOver` is a valid React event listener or if it is I'm unfamiliar with it.

**Comment by micahstubbs** [comment]
good question. here's all the react synthetic mouse events:

https://reactjs.org/docs/events.html#mouse-events

![screen shot 2018-06-12 at 10 36 48 am](https://user-images.githubusercontent.com/2119400/41306923-87d41b18-6e2c-11e8-9761-fcbc84460901.png)

**Comment by emeeks** [comment]
The more you know!

You should be able to apply events to the labels but you'd probably need to use CSS to make sure they're available in the DOM because they'll likely be in a container with `pointer-events: none`.
