### ISSUE TITLE
Broken wiki anchor link for XYFrame axes

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#26]
In the XYFrame wiki docs, the axes link should link to #axes-array instead of #axes---
https://github.com/emeeks/semiotic/wiki/XYFrame

![screen shot 2017-09-09 at 11 26 37 am](https://user-images.githubusercontent.com/1342331/30241473-16d4eab8-9552-11e7-8cad-8356cb35c45e.png)

![screen shot 2017-09-09 at 11 27 00 am](https://user-images.githubusercontent.com/1342331/30241474-1bd829bc-9552-11e7-9aeb-0af532a50302.png)

Too bad you can't submit PRs against the wiki. I'd love to help with this if I can get access.

**Comment by emeeks** [comment]
Thanks Ben I just fixed it and I changed the settings so that anyone can edit the wiki.

**Comment by bengarvey** [comment]
👌
