### ISSUE TITLE
ORFrame, Can only style axis text using CSS

### ISSUE THREAD

**Issue by arrghh1** [emeeks/semiotic#261]
Hi,

In an ORFrame, I am unable (or least can't figure out how) to pass style information to the axis using props.

In the bulletchart example on emeeks.github.io/semiotic/ the axis styling (eg. color) is passed through from comet.css

I'd like to be able to style the axis from within the component, to ensure that I don't have to copy CSS into my app / next app.

Any help in solving this would be appreciated!

**Comment by arrghh1** [comment]
Having a look at the axis to visualizationLayerBehavior/axis.js code. It should be possible to pass a style object through that goes into the svg text JSX, in fact, perhaps even a function that can vary the formatting by value (so we could make an axis tick label that changed colour depending on value for example).

I'm happy to have a look at trying this and make a pull request - but I feel like a complete noob, and I'm not sure if there would be unintended side effects (or in fact, how to even test).

**Comment by emeeks** [comment]
If you want to style the axis ticks, use `tickFormat` to return JSX SVG:
`tickFormat={d => <text style={yourStyle}>{d}</text>}`

If you want to customize the axis lines, use `tickLineGenerator` to make custom ticks:
```
tickLineGenerator={({ xy }) => (
          <path
            style={{ fill: "lightgrey", stroke: "grey" }}
            d={`M${xy.x1},${xy.y1 - 5}L${xy.x2},${xy.y1 - 5}L${xy.x2},${xy.y1 + 5}L${xy.x1},${xy.y1 + 5}Z`}
          />
        )}
```

Otherwise, the pattern for styling the regular axis elements is to use CSS.

**Comment by arrghh1** [comment]
Brilliant! I had considered tickFormat only for number formatting, not for adding a new tag. This worked perfectly.
Thanks for your help.
