### ISSUE TITLE
npm install error

### ISSUE THREAD

**Issue by frankjar** [emeeks/semiotic#262]
Hi,
 i want to install semiotic but i have this error : 

```
91 verbose stack Error: Command failed: C:\cygwin64\bin\git.EXE clone --mirror -q git://github.com/emeeks/element-resize-event.git C:\Users\antilles\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-1abf97ed\.git --config core.longpaths=true
91 verbose stack /cygdrive/c/Users/antilles/AppData/Roaming/npm-cache/_cacache/tmp/git-clone-1abf97ed/C:\Users\antilles\AppData\Roaming\npm-cache\_cacache\tmp\git-clone-1abf97ed\.git: No such file or directory
```
Where Antilles is the name of my computer.

Node 8.1.2 
npm : 6.0.0
I'm using the cygwin git executable and it's the first time i'm trying to install semiotic, i have never had this kind of error before.

Do you have an idea in order to  help me? thx a lot !

**Comment by emeeks** [comment]
Try again for me, I think it had something to do with the release tags.

**Comment by frankjar** [comment]
great, it works now ! Thank you.
 I'm happy to be able to use it now !
