### ISSUE TITLE
Most Code Pen examples down again.

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#268]
The error given is:
"Warning: React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: undefined. You likely forgot to export your component from the file it's defined in."
There are a few that are still working, one of which was still using an older version of semiotic.

**Comment by emeeks** [comment]
Yes you're right, it's broken after 1.11.4 which is odd because there's a test that should have caught that. Will dive in and also update the test.

**Comment by emeeks** [comment]
Fixed with 1.11.11.
