### ISSUE TITLE
Responsive XYFrame resize event not working

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#272]
I came across this bug earlier, but I didn't have a codepen demonstrating it yet.
https://codepen.io/ZachHaber/pen/gKKbbB
Just run the codepen and try changing the width of the browser. All of the marks just congregate to the top.
![image](https://user-images.githubusercontent.com/19843782/41796268-6b029a58-762b-11e8-99e3-790855934f63.png)
On the app I'm working on, the marks all congregate to the left as shown.
This issue shows up in versions >= 1.11.6 (I couldn't try it with 1.11.5)

I also came across an issue where the resize event for the responsive OR frame works, but the wrapped OR Frame doesn't resize to fit the area that the responsive frame covers. I don't have a codepen for that issue, however. If you need one, I can try to figure out a way to set that up (I'm updating and changing a bunch of graph sizes all at once). This issue does exist in 1.11.4.
Thanks for your support :)

**Comment by emeeks** [comment]
Fixed in 1.11.13

**Comment by ZachHaber** [comment]
Thanks for the quick fix! ✨ 
When I get a chance to, I'll try and narrow down that ResponsiveOR Frame issue I was having to figure out the cause and to get you a codepen example. That may be in a week or so, though.
