### ISSUE TITLE
Treemap keyboard nav shouldn't include root node

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#278]
Treemap keyboard nav shouldn't include root node because it doesn't convey anything useful.

**Comment by emeeks** [comment]
It does sometimes but I think it's a larger issue that you should be able to get rid of certain nav elements (or even not render them). Let me think about how to expose this. If you have any ideas about a nav/render whitelist for these kinds of network diagrams, let me know.

**Comment by mmazanec22** [comment]
Maybe when you pass in the data you can include a render or don't render key: bool at the piece data level?  So it's by line, bar, etc?

**Comment by emeeks** [comment]
Introducing `filterRenderedNodes` in 1.13.6 that takes a function and evaluates that function to remove nodes after layout but before rendering (and also removes any edges that required those nodes in layouts that have edges) which will give some control over this. Only in NetworkFrame but I could see something like this making sense for all frames.
