### ISSUE TITLE
[Question] Adding tooltip to heatmap

### ISSUE THREAD

**Issue by email2vimalraj** [emeeks/semiotic#28]
Hello,

I would like to thank you first for the awesome visualization library. My question is how do I show the tooltip of a value in the heatmap. Tried setting the `tooltipContent` on `ORFrame`, however no tooltip is shown. 

It would be great if you show some examples on how do we add the tooltip.

**Comment by emeeks** [comment]
That's a good question and one I haven't full dealt with. The summary objects themselves have no data interactivity, the only way to see hover details would be to render the points (you could set them to display none) and turn on pointHoverAnnotation. This would allow you to have hover events on the underlying points. However, I don't feel like this is sufficient and I'll give some thought as to how to properly enable hover events on summaries in the ORFrame.

**Comment by emeeks** [comment]
If you (or anyone else) has any suggestions or feature requests on how to interact with the summary objects, please feel free to post them here.

**Comment by emeeks** [comment]
That's a good question and one I haven't full dealt with. The summary objects themselves have no data interactivity, the only way to see hover details would be to turn on `pieceHoverAnnotation`. This would allow you to have hover events on the underlying points that the summary objects were built from. However, I don't feel like this is sufficient and I'll give some thought as to how to properly enable hover events on summaries in the ORFrame.

**Comment by email2vimalraj** [comment]
Yes, I did try with `pieceHoverAnnotation` which didn't help much as you guessed right. I'll see if I can make any suggestions on this issue.

**Comment by emeeks** [comment]
In 1.0.7 I plan to introduce interaction regions for summary charts, these will be the buckets for bucketized summaries (joy, violin, heatmap, histogram) and discrete regions for the boxplots.

**Comment by email2vimalraj** [comment]
Any updates on this?

**Comment by emeeks** [comment]
It's coming. I needed to make it work with all the summary types but it should be available in the next version.
![untitled](https://user-images.githubusercontent.com/495634/31368308-d0c560be-ad31-11e7-94e6-9016722ddccd.gif)

**Comment by email2vimalraj** [comment]
Awesome thanks
