### ISSUE TITLE
Some parts of lines not showing in Chrome

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#280]
In Firefox, the timeline is rendering fine, but in Chrome the lines after the second point aren't showing up (generally green and blue dots aren't being connected to their appropriate yellow dots).

![screen shot 2018-06-26 at 5 47 50 pm](https://user-images.githubusercontent.com/12260067/41941167-284df298-7969-11e8-99c7-c57993b62267.png)

<img width="1409" alt="screen shot 2018-06-26 at 5 48 02 pm" src="https://user-images.githubusercontent.com/12260067/41941178-32ec98c6-7969-11e8-8ae3-72a897b89ca1.png">

**Comment by mmazanec22** [comment]
Oof but the tooltips in Firefox are weird-- like the voronoi/interaction layer is scaled differently/translated differently than the visualization layer or something like that

**Comment by mmazanec22** [comment]
Weirdly, they show up just fine if I make a nauseatingly weird timeline by assigning incrementing y values to each event in a sequence.

<img width="1185" alt="screen shot 2018-07-03 at 4 55 18 pm" src="https://user-images.githubusercontent.com/12260067/42244179-f0abc74c-7ee1-11e8-872d-4bd3370ef892.png">

**Comment by mmazanec22** [comment]
This... just magically fixed itself?  Because Chrome fixed it?  Or I did something?

<img width="607" alt="screen shot 2018-07-10 at 2 32 39 pm" src="https://user-images.githubusercontent.com/12260067/42530052-2b5d25b8-844e-11e8-83f3-9425c2d3ef44.png">
<img width="744" alt="screen shot 2018-07-10 at 2 32 48 pm" src="https://user-images.githubusercontent.com/12260067/42530053-2b6ee78a-844e-11e8-8889-423905ce47d9.png">

**Comment by emeeks** [comment]
They must have heard I was implementing a fix. I take full credit for this. Now I have to rollback the fix in the next version... But first I'll check to make sure.

**Comment by emeeks** [comment]
v1.11.14 Forces all basic lines to have the `simpleLine` prop, which means they won't be subject to this bug but also means they won't do that cute animated transition into stacked charts but that's a small price to pay.
