### ISSUE TITLE
Create series of lines/points/areas by passing multiple accessors instead of multiple arrays

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#281]
I have run into the case where I want a set of lines that are just based on different attributes of a set of data. Right now I would need to duplicate the data multiple times to send this as a lines array, but it would be nice to be able to send an array of accessors instead that the frame would iterate over. So far I've only come across this use case for XYFrame not sure how extensible it is for ORFrame.

**Comment by emeeks** [comment]
In v1.12. One aspect I think that's missing is some way of decorating the resulting data so that you knew which accessor made it. But we can think about that in the future.
