### ISSUE TITLE
TooltipContent Node Reference

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#282]
I was wondering, would it be possible to pass a reference of the node that triggers the tooltip into the tooltipContent function so I can use a Semantic UI Popup as my tooltip base?
The reason I'd like to do that is because I'm having issues with the tooltips going out of view underneath other components, and in this case I believe it isn't solvable solely through the z-index. So, my options were to use a smarter tooltip/popup design (e.g. semantic ui popup) or to figure out how to make the tooltips smarter through pure css and I am nowhere near that level of css.
Thanks for everything :)

**Comment by emeeks** [comment]
So you need the actual node itself like the `<path>` element that is the voronoi?

**Comment by ZachHaber** [comment]
So, the way that the semantic ui popups work, is (I believe): you can give them a context which is a reference to a react element. It uses the x/y position of that react element and it's location in the DOM. Without that context for it to be bound to, it just shows up at the top-right corner of the screen. I think the best possibility would be to get the frame-pieces/ the reference to the visualization layer element that the <path> element corresponds to, as the <path> element would not actually be at the correct location for XY frames.

**Comment by ZachHaber** [comment]
I got it to work! I ended up using <Popup trigger={<div />} open key={`${d.x},${d.y}`}></Popup>
Which created the div as the context point in the correct spot. The key is needed to make sure it doesn't try to reuse the popup as that makes it stay in the same spot. Which means that I don't need the reference 😃. Thank you for your time in working on this!

**Comment by emeeks** [comment]
Oh interesting. Would love to see an example of this.

**Comment by ZachHaber** [comment]
Here's an example!
https://codepen.io/ZachHaber/pen/bjbazQ
It took a bit to set up (Apparently Semantic UI's newest version causes it to fail, so I had to use 0.81.3).
