### ISSUE TITLE
XYFrame Voronoi Interaction Resize Issues

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#283]
I've noticed that resizing the graph in the X or Y directions causes issues with the voronoi interaction regions not being updated. For instance on the graph below, resize the browser rather significantly and then see where the interaction regions are.
https://codepen.io/ZachHaber/pen/gKKbbB
Thanks for your help!

**Comment by emeeks** [comment]
Fixed in v1.11.14 let me know if you see any issues.
