### ISSUE TITLE
Debounce the Responsive event in ResponsiveFrame

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#286]

**Comment by emeeks** [comment]
onEnd might be acceptable if that can happen

**Comment by ZachHaber** [comment]
If you don't have any super-custom parts to your resizer, this seems to work pretty well for me, and it has a debounce feature in it.
https://github.com/ctrlplusb/react-sizeme#readme
Hope this helps! 😄

**Comment by emeeks** [comment]
I like the look of that but I spent so much time finding various issues with resize libraries that I don't want to get into it with another library right now. I just added a simple timeout debounce that defaults to 200ms and that the user can pass a `debounce` property to any responsive frame to change the number of ms.

**Comment by emeeks** [comment]
Available in v1.11.14
