### ISSUE TITLE
Responsive Frames Not Responsiving

### ISSUE THREAD

**Issue by ZachHaber** [emeeks/semiotic#290]
I tried updating to the new version, and I believe that the new debouncing feature is causing this issue:
When you resize the page (i.e. more than 1 graph has to resize), then only one of the graphs will resize (typically the one that renders later). This still occurs when debouncing is set to 0.
https://codepen.io/ZachHaber/pen/mjyXPB
https://codepen.io/ZachHaber/pen/LdqaRJ
Thank you!

**Comment by emeeks** [comment]
Hey Zach, when I try this pen it seems like they're responsiving just fine. I'll get a local instance going to see if I can reproduce it but if you could take a look at the pen and if it doesn't respond the same way let me know your browser and such. Thanks!

![itt_muse_2](https://user-images.githubusercontent.com/495634/42580599-cb9d4134-84df-11e8-8140-b1aeccc7239f.gif)

**Comment by ZachHaber** [comment]
I might not have saved it? Try again. There should also be two of that frame on it, neither with responsiveHeight active.

**Comment by emeeks** [comment]
I see it with the XYFrame. For me, the OrdinalFrame seems to respond fine but I'll get a fix in shortly.

**Comment by ZachHaber** [comment]
Alright, thanks. I'll let you know if the issue persists in the OrdinalFrame after the fix. Also I updated the ORFrame one again, to make it so you could easily see both graphs without scrolling. The interesting thing is that the responsive frame was grabbing the full height of the viewport but only using 300px of it since I turned off responsive height.

**Comment by emeeks** [comment]
I found the problem and will have a fix in shortly.

**Comment by ZachHaber** [comment]
Looks good! Fixed in 1.11.15 XD
