### ISSUE TITLE
Painty throughs an error when rendering chord

### ISSUE THREAD

**Issue by demartsc** [emeeks/semiotic#292]
I am getting this error when using painty render method with chord diagram. I have tried a few times and keep getting this, sketchy and normal render methods are working ok though. 

<img width="582" alt="painty error with chord" src="https://user-images.githubusercontent.com/22157638/42738897-bcb9d2c2-8840-11e8-9ad0-a6da7e6967b5.png">

**Comment by emeeks** [comment]
Fixed in 1.13.0
