### ISSUE TITLE
SOLVED: tickFormat doesn't work on ORFrame?

### ISSUE THREAD

**Issue by MikaHamalainen** [emeeks/semiotic#294]
I have a XYFrame line chart with axis options:

import Numeral from "numeral"; // I'm using numeral.js
...
axes={[{ orient: "left", tickFormat: d => Numeral(d).format("0.[0]a") }, {...}]}

This works just fine, but when trying to do same in ORFrame bar chart it doesn't work. Actually it renders default value and tickFormat value on top of each other... 

![image](https://user-images.githubusercontent.com/1428467/43007587-6dffa012-8c41-11e8-95c4-2277201ebe93.png)

**Comment by emeeks** [comment]
Can you post your settings? I can't reproduce this and it looks like you might have sent two axes to the `axis` element (which is legal, `axis` can take an array of axis objects in case you want to have different overlapping axes simultaneously).

**Comment by MikaHamalainen** [comment]
import React from 'react';

import moment from 'moment';
import Numeral from "numeral";

import  { ResponsiveOrdinalFrame} from 'semiotic';
import './ChartCommons.css';


export default props => {
  const { fullData, filteredData } = props;  
  const string = Numeral(1000).format('0 a');
  console.log(string)
    
  return (
    <ResponsiveOrdinalFrame
      title={"Store & Online Sales"}
      className="bar"
      size={[400, 400]}
      responsiveWidth={true}
      type={{type: "bar"}}
      data={filteredData ? filteredData : fullData }
      oAccessor={d => +d.dd}
      rAccessor={d => +d.amo}
      // summaryType={{type: "Violin"}}// "heatmap", "boxplot", "histogram", "joy", "contour", "violin"
      style={(d, i) => ({ fill: d.color, stroke: "white" })}
      oPadding={5}
      margin={{ top: 50, right: 20, bottom: 40, left: 100 }}
      pieceHoverAnnotation={true}
      tooltipContent={d => {
        return (
          <div className="tooltip-content shadow">
            {moment(+d.tim).format("dddd DD.MM.YYYY")}<hr /><br />
            {d.name} sales: {new Intl.NumberFormat('fi-FI', { 
              style: 'currency', 
              currency: 'eur',
              minimumFractionDigits: 0, 
              maximumFractionDigits: 0 
            }).format(+d.amo)}
          </div>
        )
      }}
      axis={[{ orient: "left", tickFormat: d => Numeral(d).format("0.[0]a") },{ orient: "bottom"}]}
      oLabel={d => (
              <text transform="translate(-5,0)rotate(0)">{d}</text>
            )}
    />
  );
}

**Comment by emeeks** [comment]
Yeah there's the issue here:

```
axis={[{ orient: "left", tickFormat: d => Numeral(d).format("0.[0]a") },{ orient: "bottom"}]}
```

You're sending one axis to the "left" and one axis to the "bottom" but because the orientation of the chart is vertical, the bottom axis is being forced to be on the left. Just remove `,{ orient: "bottom" }` and you'll be good.

Each object in the axis array represents settings for a whole new axis. For OrdinalFrame, it overrides an invalid axis (since you can only have an axis for the numerical range, it uses `oLabel` for the column/row labels) orientation with a valid orientation, giving you two left axes in this case.

**Comment by MikaHamalainen** [comment]
Solved. Thank You!
