### ISSUE TITLE
Website hamburger menu is not obvious

### ISSUE THREAD

**Issue by jayphelps** [emeeks/semiotic#3]
Mostly just an FYI.

I saw your talk where you presented this and then went to the website to try the examples you presented. So I assumed I should click "API Docs" or "Tutorials" but they both take you to the github wiki. Because I specifically remember examples on the website, I then recalled there being a menu on the left, so I only then started to look around and noticed the hamburger menu icon.

Maybe most will notice it..just an FYI that I only went looking for it because I knew those examples were _somewhere_, but others may only look at the API Docs and Tutorials since those buttons are prominent.

Simple solution would be to always show the side menu and maybe move the API Docs and Tutorials buttons into there too. Or you can ignore me hehe. 🤡

**Comment by emeeks** [comment]
Yeah I felt the same thing but when it's opened on mobile with the menu open it looks like hell so for now I added a big "Interactive Examples" button that will show up in the next docs push. Hopefully that will help.
