### ISSUE TITLE
Default aria descriptions for pieces should use the axis label formatter

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#301]
Ordinal frame aria descriptions for pieces should use the axis label formatter rather than the values themselves.

Case 1: an ordinal frame with bars positioned by month, where the x axis is labeled "10/2016," "11/2016," etc.  The screen reader reads out the timestamp, which is confusing because the actual measure isn't precise to that level.

Case 2: an ordinal frame where the y axis is in dollars, and the number loses some meaning without that label.

**Comment by emeeks** [comment]
This should be in 1.13.2 please let me know if you see any issues.
