### ISSUE TITLE
More child possibilities for FacetController 

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#308]
Yay FacetController!  The two child options that I have found myself needing are:
- FacetController recognizing which children belong to semiotic and which are just divs and such helping out
- Responsive frames

**Comment by emeeks** [comment]
I noticed the div issue and I will have it ignore anything that isn't supported. I didn't realize with Responsive frames that I wasn't passing the displayName through, I'll fix that, too.

**Comment by emeeks** [comment]
Responsive Frames are handled properly and non-frame elements are ignored as of 1.13.4
