### ISSUE TITLE
Enable additional customEdgeType for Tree/Cluster Network Frame

### ISSUE THREAD

**Issue by demartsc** [emeeks/semiotic#311]
Enable sigmoid like edge for tree and cluster network frame. Similar to what we see in some of Bostock’s examples. https://bl.ocks.org/mbostock/4339184

**Comment by emeeks** [comment]
Implemented a `"curve"` edgeType in NetworkFrame in 1.14.0 that uses the D3 linkHorizontal and linkVertical under the hood. I still need to better understand linkRadial before that works.

**Comment by demartsc** [comment]
Awesome can’t thank you enough!
