### ISSUE TITLE
Cursor: pointer when customClickBehavior is set

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#326]
<img width="1127" alt="screen shot 2018-09-14 at 11 13 28 am" src="https://user-images.githubusercontent.com/12260067/45559003-51ba8a80-b80f-11e8-9977-c05f82d4d035.png">

I'm using this (obviously unfinished) NetworkFrame/partition as a multiselect/filter for hierarchical data.  I'm using customClickBehavior to do this.  I'm afraid users won't realize they can click the visualization to filter if the cursor isn't a pointer.  Setting that in node style isn't working because of the interaction layer.

Maybe when customClickBehavior is set the cursor should automatically be a pointer for the pieces?  Or at least maybe there should be a way to set the cursor?  Or maybe nodeClass should also be applied to interaction and annotation layer nodes?

**Comment by emeeks** [comment]
1.14.5 now has cursor: pointer for any interaction regions when customClickBehavior or customDoubleclickBehavior are turned on.
