### ISSUE TITLE
Visualizing directed cyclic graphs

### ISSUE THREAD

**Issue by strictlymomo** [emeeks/semiotic#332]
Any plans to introduce this feature?

**Comment by emeeks** [comment]
Could you explain to me the use case?

**Comment by strictlymomo** [comment]
_(edited title to more accurately reflect the use case)_

I am trying to visualize directed cyclic graph data with a React UI. In my research I've found most use cases involve a two-step process:

1) establish a layout model using a charting algorithm like dagre or ELKjs;
2) visualize the layout in a render engine, a la dagre-d3 or other libraries.

Is it possible to prepare such a layout model and visualize it via a Semiotic graph component?

**Comment by emeeks** [comment]
You can import dagre and create a dagre graph and `NetworkFrame` will handle it:

https://emeeks.github.io/semiotic/#/semiotic/customnode

**Comment by strictlymomo** [comment]
Respect!  I did not see this before.  Thanks very much!
