### ISSUE TITLE
[Question] Gradient area chart

### ISSUE THREAD

**Issue by MarcMagnin** [emeeks/semiotic#333]
Hi,

Is it possible with semiotic to have gradient area chart within canvas like this echarts sample? : https://ecomfe.github.io/echarts-examples/public/editor.html?c=area-simple

Many thanks,
Marc

**Comment by emeeks** [comment]
Sure you can, you just need to use two features in XYFrame:

`additionalDefs` allows you to pass in a gradient.
`lineType` has an optional `y1` prop that you can set to 0 to create an area chart. Here's a pen:
https://codepen.io/emeeks/pen/zmoVgW

<img width="1415" alt="screen shot 2018-10-08 at 9 32 48 am" src="https://user-images.githubusercontent.com/495634/46621742-27da4800-cadd-11e8-8259-150a1d3fd327.png">

**Comment by MarcMagnin** [comment]
An extra question on that, is it possible to get a gradient with a canvas lines?
Many thanks!

**Comment by DigitalMarc** [comment]
Hey! I would like to use this feature as canvas is mandatory in my scenario (lot of lines on the same chart so performances are a problem with SVG). Any update on this one?
