### ISSUE TITLE
[Question] Disable transitions

### ISSUE THREAD

**Issue by MarcMagnin** [emeeks/semiotic#334]
Hey,

What is the best way to disable transition animations? 

Many thanks!

**Comment by emeeks** [comment]
The best way is to use the `baseMarkProps` attribute of a frame to set all marks generated by the frame to not have animations. Which is done like this:

`baseMarkProps={{ forceUpdate: true }}`

Another way would be to use canvas rendering but if you want to do it with SVG use the above. `baseMarkProps` takes an object that is spread to all marks generated by the frame and `semiotic-mark` honors a `forceUpdate` prop that causes it to skip animation.

**Comment by MarcMagnin** [comment]
Cheers,
I'm looking for canvas over svg to get the best perfs (got plenty of charts to render). How do you recommend to deal with the canvas rendering way?

**Comment by emeeks** [comment]
Yes that will work but unfortunately there's only one canvas layer and it's below SVG. At some point I'll provide the ability to compose SVG + Canvas better, including layers of each, but that's still a ways out.
