### ISSUE TITLE
Different value passed to nodeSizeAccessor based on whether or not separation is set in networkType

### ISSUE THREAD

**Issue by mmazanec22** [emeeks/semiotic#343]
With separation set:
<img width="592" alt="screen shot 2018-10-24 at 9 54 42 am" src="https://user-images.githubusercontent.com/12260067/47435679-19de2580-d773-11e8-8e93-d134d218b8d6.png">

Without separation set:
<img width="532" alt="screen shot 2018-10-24 at 9 55 09 am" src="https://user-images.githubusercontent.com/12260067/47435697-21053380-d773-11e8-87d2-244628a97d03.png">

**Comment by emeeks** [comment]
I bet I'm sending the bound data and not the bound data + the decoration from d3-hierarchy. I'll take a look.

**Comment by emeeks** [comment]
Should be fixed in 1.15.7
