### ISSUE TITLE
More metadata required when using an array of rAccessors

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#346]
Using multiple rAccessor s doesn’t pass the right kind of index so that you can color your data.
My rAccessor = [“tweets”, “retweets”]
But in style it shows, for the d and the i 
```
 style: (d, i, t) => {
    console.log(d, i, t)

    return { fill: colorHash[d.action], stroke: "white" }
  }
```
![image](https://user-images.githubusercontent.com/1449837/47968479-6ea95800-e01f-11e8-818b-b5ca35edab81.png)
There needs to be some kind of index or key to know which of the accessors each styled piece is referring to.

**Comment by emeeks** [comment]
In 1.15.8 points and lines are decorated with `xIndex`, `yIndex`, `lineIndex` corresponding to the array position of xAccessors, yAccessors and lineAccessors. Likewise, `OrdinalFrame` decorates pieces with `rIndex` and `oIndex` which correspond to which of the accessors generated them.
