### ISSUE TITLE
Setting upper limit for rExtent for ORFrame type: "point" causes the domain to be just min/max

### ISSUE THREAD

**Issue by tomshanley** [emeeks/semiotic#37]
If I set rExtent={[0,1]}, then the domain reverts to the min and max of the dataset (my data in this example are between 0 and 1).

If I set rExtent={[0]} (or rExtent={[0, undefined]}), then the domain extent correctly sets to 0 and the max of the dataset.

This occurs when I set type: "point".  If I set type: "bar", then rExtent={[0,1]} works fine, ie domain extent sets to 0 to 1.

**Comment by emeeks** [comment]
This should be fixed in 1.1, which should be published shortly. There was some nonsense going on in the rExtent logic that got sorted out.
