### ISSUE TITLE
Show force graph networkframe iterations while they happen

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#376]
I'm using the ResponsiveNetworkFrame for a project I have it set for 400 iterations 

```
          <ResponsiveNetworkFrame
              size={[ 300, 700 ]}
              responsiveWidth={true}
              edges={this.network.links}
              nodes={this.network.nodes}
              edgeStyle={(d) => ({ stroke: colors[d.relation], fill: colors[d.relation], opacity: 0.5, strokeWidth: '1px' })}
              nodeStyle={d => getNodeStyle(d)}
              networkType={{ type: 'force', iterations: 400, edgeStrength:0.09 }}
              edgeType={'arrowhead'}
              nodeSizeAccessor={d => 6}
              zoomToFit={true}
              nodeIDAccessor={"id"}
              nodeLabels={d => d.name}
              hoverAnnotation={true}
              tooltipContent={d =>~ 
                <div className="tooltip-content" >
                  <p>{d.id}</p>
                  <p>{d.name}</p>
                </div>
              }   
              legend={{legendGroups}}
              margin={{left: 25, top: 20, bottom: 20, right: 120}}
          />  
```

To look good it needs a few thousands, but unlike D3 it doesn't seem to do those iterations live. It runs them before the first paint so it appears slow. It I resize the frame it will run through all the iterations again and after 3 or 4 times the graph looks nice. What's odd is that if I set iterations to a very high number, say 10000. It takes even longer to paint, but still doesn't look as good as a shorter iterations value and re-sizing a few times.

So, is there a way to run the iterations live so we can see them, or is there a way to trigger the iterations to start again like resizing does (ie. can I trigger it automatically)?

**Comment by bengarvey** [comment]
If you want to see a live example:
HUGE SPOILERS IF YOU HAVEN'T SEEN EVERY EPISODE OF THE WIRE
http://plotdevice.bengarvey.com/wire

**Comment by emeeks** [comment]
That will be a challenge--the internals are pretty baked in for a pre-calculated force simulation--but I'll take a look and see what I can do.

**Comment by bengarvey** [comment]
I figured out a very jankey way to make this work.
Spoilers if you haven't seen The Wire
http://plotdevice.bengarvey.com/wire

**Comment by bengarvey** [comment]
Got this working even better on mobile, so closing this out
http://plotdevice.bengarvey.com/wire
