### ISSUE TITLE
nodeAndEdgeListFromHierarchy expose function

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#378]

**Comment by emeeks** [comment]
You can import `nodesEdgesFromHierarchy` from Semiotic it takes a (`rootNode`, `idAccessor`) where the `rootNode` is a d3-hierarchy processed like hierarchy (meaning it has things like `.descendents()` and `idAccessor` is a function that takes each node and returns an ID, which is used internally to set the keys for the edges (and so you should be able to pass nothing for that and ignore it).

This is available in `1.16.5`
