### ISSUE TITLE
Sankey Direction bugs

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#379]
Setting direction: "right" and "down" display properly
![screen shot 2019-02-06 at 7 39 37 am](https://user-images.githubusercontent.com/1449837/52352910-5fe98d00-29e2-11e9-834e-839fd76736c9.png)

Setting direction: "left"
![screen shot 2019-02-06 at 7 37 30 am](https://user-images.githubusercontent.com/1449837/52352889-5102da80-29e2-11e9-8033-36d7ef46f83a.png)

Setting direction: "up"
![screen shot 2019-02-06 at 7 37 53 am](https://user-images.githubusercontent.com/1449837/52352879-4b0cf980-29e2-11e9-9c80-c71cf768283a.png)

**Comment by emeeks** [comment]
This was a mistake on my part, sankey should only honor `projection` not `direction`. The next version will ignore `direction` and honor `projection` settings of `horizontal` and `vertical` (you can change the left/right by changing the direction of the data)

**Comment by emeeks** [comment]
This is rolled out in `1.16.5`
