### ISSUE TITLE
[Bug] XYFrame: Unexpected points coordinates when using lineStyle="stackedarea"

### ISSUE THREAD

**Issue by LaurentChion** [emeeks/semiotic#383]
Hi,
I have found a bug when rendering points on `stackedarea` lines charts.
## Current behavior
When using `lineType="stackedarea"` and `showLinePoints={true}` properties, y coordinates value are wrong.

## Expected behavior
Using `lineType="stackedarea"` should not interfere with points showed by `showLinePoints={true}`

#### Code
```js
import React from 'react'
import {XYFrame} from 'semiotic'

const lines = [
    {
        id: 'line-1',
        data: [  
            [0.0, 0.0],
            [0.3,10.0],
            [1.0,8.0]
        ],
        color: "#00a2ce"
    },
    {
        id:'line-2',
        data: [
            [0.0, 6.0],
            [0.3, 2.0],
            [1.0, 8.0]
        ],
        color: "#cea200"
    }
]

export default (props) => (
    <XYFrame 
        title="Test"
        lines={lines}

        lineDataAccessor={ "data" }
        pointStyle={{
            stroke:"red",
            strokeWidth: 25
        }}
        lineStyle={ d => ({
            stroke: d.color,
            fill: d.color
        })}
        showLinePoints={true}

        lineType="stackedarea"

        margin={{ left: 80, bottom: 50, right: 10, top: 40 }}
        axes={[
            {
            orient: "left"
            },
            {
            orient: "bottom"
            }
        ]}
        hoverAnnotation={true}

    />
)
```

#### With lines:
![image](https://user-images.githubusercontent.com/20227356/52793873-ff57f100-306e-11e9-8503-c9f5b6e34fd6.png)

#### With stacked area:
![image](https://user-images.githubusercontent.com/20227356/52793843-f0713e80-306e-11e9-8f82-585709ceb8fd.png)

#### With line:
![image](https://user-images.githubusercontent.com/20227356/52793918-17c80b80-306f-11e9-899c-d16be523c6a1.png)

#### With stacked area:
![image](https://user-images.githubusercontent.com/20227356/52794080-6e354a00-306f-11e9-925b-7ffa6fc0d39c.png)

Thanks

**Comment by emeeks** [comment]
Hi Laurant, those are the control points for the hover behavior. Is your expectation that the points would appear at the top of the area rather than the middle of the area?

**Comment by LaurentChion** [comment]
Thanks for your quick answer :smiley: 

Yes exactly. I thought this boolean was for this feature but now you are telling me it is for the hover behavior I understand why points are in the middle of the upper and lower curve.

Is there a way to highlights data point on top of the area? (I will look further in the documentation but I think its link to pointStyle parameter)

**Comment by emeeks** [comment]
In `1.16.7` the `showLinePoints` prop will now accept `true | "top" | "bottom"`. If you send `top` or `bottom` it will determine where on the area the points are placed. Thanks for bringing this up, I think this is a good feature.
