### ISSUE TITLE
OrdinalFrame - Make All Summary Data Accessible to Custom*Behaviors and tooltipContent functions 

### ISSUE THREAD

**Issue by torioLuz** [emeeks/semiotic#389]
The purpose is to be able to show the summary data in the custom tooltip or event callbacks. E.g. Would like to know the all the quartile values for box plot if hovered. 

I saw that the library offers SummaryHoverAnnotation function, but the data supplied is just the hovered summary data point.

**Comment by emeeks** [comment]
Makes a lot of sense.

**Comment by emeeks** [comment]
In 1.17.0 because of your PR
