### ISSUE TITLE
Website hangs on xyframe change fixed extent params 

### ISSUE THREAD

**Issue by markov00** [emeeks/semiotic#4]
Hi the website hangs(seems an infinite loop) at the XYFrame example page [https://emeeks.github.io/semiotic/#/semiotic/xyframe](https://emeeks.github.io/semiotic/#/semiotic/xyframe) when I try to change the fixed extent param .
Seems affected by only with the `line` data type

**Comment by emeeks** [comment]
This was more simple than I thought, the extent was being set to a range that there weren't any values within. There should be some handling for when the users sends bad extents but for now I've updated the docs to have an appropriate extent.
