### ISSUE TITLE
Two lines, different axes scales in the same XYFrame

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#40]
Not sure if this is a philosophical issue or not. Is there a way to use two axes in the same XYFrame for two lines?

eg.
Scale one line 0-100 and another 0-1 but overlay them on top of each other. I can obviously do this with separate frames, but it seems like it should be possible with one frame.

**Comment by bengarvey** [comment]
Nevermind. It appears the right way to do this is with two frames
https://emeeks.github.io/semiotic/#/semiotic/barline

**Comment by bengarvey** [comment]
![screen shot 2017-09-23 at 8 20 25 am](https://user-images.githubusercontent.com/1342331/30773148-b158d928-a038-11e7-9b7f-5093302a83e1.png)

Made it work. Not sure yet how to get hover animations to work with overlayed frames yet, but I'll figure that out.

**Comment by emeeks** [comment]
Yes it's a philosophical decision not to have multiple axes. The problem with layering like this is you only have the interactivity on the top chart. You can get around it by normalizing the datasets and then via tooltip formatting and axis formatting you can show the axes of the original data. This is not the best pattern but it's there.
