### ISSUE TITLE
Annotation labels aren't updating

### ISSUE THREAD

**Issue by darthmall** [emeeks/semiotic#48]
I'm generating annotations dynamically to reflect the values of the slider below each of these linked charts. The x-position of the annotation is updating, but the label is not.

![annotation_label_bug](https://user-images.githubusercontent.com/52247/30784918-d9f18c10-a12b-11e7-9bbd-bb74146566e5.gif)

You can see that even though the annotation moves, the label still says "2".

**Comment by emeeks** [comment]
Which version are you using?

**Comment by darthmall** [comment]
I have version 1.1.0.

**Comment by emeeks** [comment]
So I checked with Susie and this looks like an outstanding bug in `react-annotation` that she won't be able to address for a couple weeks. I'm going to see if I can implement an interim fix in the meantime.

**Comment by darthmall** [comment]
Great, thanks. I'm in no great hurry, just wanted to raise the issue.

∴ Evan

**Comment by emeeks** [comment]
I've added a simple fix that gives randomized keys to all the <Annotation> components created by the Frames. This is available in `1.1.2` When Susie gets a chance to update `react-annotation` I'll pull this out.

**Comment by susielu** [comment]
This should be updated in `0.0.1-4` of `react-annotation` let me know if you have any problems with updating it.

**Comment by artemverbo** [comment]
@susielu hi, I believe this issue could be back again, I'm using `semiotic@1.19.6`, and `react-annotation@2.1.6`, having similar problems with all the things re-rendering,  except annotation label. I do use a responsive frame and on resize, the label is rendered correctly though.
```
annotations: [
      {
        type: AnnotationCalloutCircle,
        note: {
          title: `${value}`,
          orientation: 'topBottom',
          align: 'middle',
          lineType: null,
          ...
```
Thanks for all the awesome work with d3/react-annotation and Semiotic!
