### ISSUE TITLE
ORFrameConnector

### ISSUE THREAD

**Issue by sa-mm** [emeeks/semiotic#51]
Can I adjust the stroke width from here?

```
<ORFrame
   connectorType={d => d.type}
   connectorStyle={d => ({ fill: d.source.color, strokeWidth: 10 })}
/>
```

`strokeWidth: '10'` doesn't appear to do much either.

Some of the examples show thick line connecting the points. I'd like to replicate that.

**Comment by emeeks** [comment]
The connector generated is based on the `type` you've defined for the frame, so lines for `point` and `swarm` and filled areas for `bar`. When I set strokeWidth to 10 I see it just fine:
![screen shot 2017-09-27 at 2 54 15 pm](https://user-images.githubusercontent.com/495634/30939857-cf45d25c-a393-11e7-9de7-e67b6c21427c.png)

In your code above you don't define a stroke color, so maybe your CSS has it set to `none`? Or maybe you don't have a type defined? In which case the connector doesn't know what to draw from and to. If you can point me at a simple example somewhere I'll take a look.

**Comment by sa-mm** [comment]
Thanks! I didn't have stroke set. Yup.

I also didn't know what the parameter in the function referred to. I thought `source` was some key in your data.  Anyways, thanks again!

**Comment by emeeks** [comment]
Ah, I will check to see if this is documented. The connector object is simple `{source, target}` where `source` is the piece in column A and `target` is the piece it connected to according to your rule in column B. Hope that makes sense.

**Comment by sa-mm** [comment]
Yup, that makes sense. Do you think you’ll keep the naming (source/target) pretty stable for that? I’m using it on a color hash to set the line color:

`stroke: colorHash[d.source.type]`

**Comment by emeeks** [comment]
Yes I don't see the connector quasi node changing any time in v1.
