### ISSUE TITLE
Cannot import any modules from 'semiotic'

### ISSUE THREAD

**Issue by zettadam** [emeeks/semiotic#56]
HI I just installed `semiotic` as I wanted to evaluate how I could create simple visualizations using Semiotic framework.

Here's the code I created for a simple AreaChart:

```
import React from 'react'
import { XYFrame } from 'semiotic'

console.log( 'XYFrame', XYFrame)

const AreaChart = (
  colors = [],
  data = [],
  height = 400,
  marginTop = 60,
  marginRight = 20,
  marginBottom = 60,
  marginLeft = 60,
  width = 700,
  xAccessor = 'x',
  yAccessor = 'y'
) =>
  <XYFrame
    size={[ width, height ]}
    lines={ data }
    lineStyle={ d => ({ fill: d.color, fillOpacity: 0.5, stroke: d.color, strokeWidth: '3px' }) }
    xAccessor={ xAccessor }
    yAccessor={ yAccessor }
    margin={{
      top: marginTop,
      right: marginRight,
      bottom: marginBottom,
      left: marginLeft
    }}
    axes={[
      { orient: 'left', tickFormat: d => d },
      { orient: 'bottom', tickFormat: d => d }
    ]} />

export default AreaChart
```

`console.log` line returns `undefined` so I'm wondering if npm package is actually exporting modules properly. Am I doing something wrong?

I am using the latest version of semiotic (1.1.3) React 16.0, Webpack 3 with NodeJS v.8.6.0. I am using other 3rd-party npm packages with this setup, but I only see this error with semiotic, so I suspect that `import { XYFrame } from 'semiotic'` even though it seems right and documentation shows that this is how modules should be imported from semiotic is problematic as it stands.

**Comment by zettadam** [comment]
I have switched to CommonJS modules:

```
const Semiotic = require('semiotic')

console.log( 'Semiotic', Semiotic)
```

and I see this object in the Console:

```
{
   Annotation: undefined,
   AnnotationLayer: undefined,
   Axis: undefined,
   Brush: undefined,
   DebugComponent: undefined,
   DividedLine: undefined,
   DraggableMark: undefined,
   InteractionLayer: undefined,
   Legend: undefined,
   Mark: undefined,
   MarkContext: undefined,
   MiniMap: undefined,
   MinimapXYFrame: undefined,
   NetworkFrame: undefined,
   ORFrame: undefined,
   ResponsiveMinimapXYFrame: undefined,
   ResponsiveNetworkFrame: undefined
   ResponsiveORFrame: undefined,
   ResponsiveSmartFrame: undefined,
   ResponsiveXYFrame: undefined,
   SmartFrame: undefined,
   VisualizationLayer: undefined,
   XYFrame: undefined,
   calculateDataExtent: undefined,
   funnelize: undefined,
   __esModule: true
}
```

So it seems that `semiotic` has correct structure, but all modules are `undefined`. I'm wondering if using `react-create-app` and `react-scripts` is part of the problem.

**Comment by emeeks** [comment]
That's very strange indeed. I've used `react-create-app` in the `semiotic-examples` repo and haven't run into any problems but `react-scripts` maybe? I assume you've installed other libraries and they're fine?

**Comment by emeeks** [comment]
At Netflix we're using an app with `react-scripts` and `semiotic` and it doesn't show any issues.
