### ISSUE TITLE
Add simple examples

### ISSUE THREAD

**Issue by emeeks** [emeeks/semiotic#6]
Add examples in the interactive documentation that show the code for minimal, effective traditional charts:

* Bar Chart (Stacked Bar Chart separately)
* Pie Chart
* Line Chart

**Comment by fengshuo** [comment]
In the `XYFrame` tutorial [here](https://github.com/emeeks/semiotic/wiki/Visualizing-Time-Series-Data), the code snippet shows:  
```
<XYFrame
   lines={data}
   xAccessor="timestamp"
   yAccessor="sales"
   xScaleType={scaleTime()}
   lineDataAccessor="data"
   lineStyle={d => ({ stroke: d.color, fill: d.color })}
/>
```
but it will throw `The prop size is marked as required in `XYFrame`, but its value is undefined`, would be easier for first time user if the code snippet has what's on the [example page](https://emeeks.github.io/semiotic/#/semiotic/xyframe), like adding `size` prop, 😀

**Comment by emeeks** [comment]
What a silly mistake, thanks for catching that.

**Comment by sa-mm** [comment]
Also, that tutorial might be easier to follow if the constant and key in the constant weren't both called "data."

**Comment by bengarvey** [comment]
Include the data if possible in the code examples.

**Comment by emeeks** [comment]
First simple tutorial for a bar chart:
https://emeeks.github.io/semiotic/#/semiotic/creatingbarchart
More coming soon.

**Comment by emeeks** [comment]
Two more examples:
Line chart:
https://emeeks.github.io/semiotic/#/semiotic/creatinglinechart
Pie/Donut/Nightingale Chart
https://emeeks.github.io/semiotic/#/semiotic/creatingpiechart

**Comment by zettadam** [comment]
Would it be possible to make `data` passed to visualizations easier to understand? In many examples, it seems a little magical.

For example, I took a look at `histogram` summaryType in ORFrame demo. The docs are unclear how one would format data for this type of visualization. I understand that they are 'funnelized' because I tried to follow the source code, but I failed to find how it is processed.

I created a HistogramChart based on that example and copied generated `data`, but the output visualization was nowhere near what I expected.

**Comment by emeeks** [comment]
This is a good point @zettadam. I'll put together a summaryType walkthrough and be very specific about this. I think the ORFrame data abstraction is the most "magic" part of Semiotic based on feedback. I think it's a good model but I know I need to explain it better.

**Comment by curran** [comment]
Has anyone had success with Semiotic on bl.ocks.org?

Perhaps possible using [babel-standalone](https://github.com/babel/babel/tree/master/packages/babel-standalone).

**Comment by emeeks** [comment]
People have shared examples using StackBlitz and I know there was some talk about creating an unpkg version, which would make it blocks friendly.

**Comment by curran** [comment]
Just discovered this https://github.com/emeeks/semiotic-examples

**Comment by emeeks** [comment]
Yeah, it's my Twitch repo. I've been so irregular with Twitch that I haven't sort of mentally integrated the results with the rest of Semiotic, but it's getting to be a growing set of examples.

**Comment by curran** [comment]
Nice! Are there video recordings of the Twitch sessions?

**Comment by emeeks** [comment]
The videos are stored for two weeks at https://www.twitch.tv/elijahmeeks/videos/all and I've downloaded the old ones and I need to edit them and put them on Youtube.

**Comment by timelyportfolio** [comment]
@curran, also you might want to follow along #70 for the standalone discussion for usage with bl.ocks or blockbuilder.

**Comment by timelyportfolio** [comment]
Here is a quick example http://blockbuilder.org/timelyportfolio/2657963ea577afe43b6eeab798b31c67 using my temporary standalone version of Semiotic.  I have not worked out the CSS part yet.

**Comment by curran** [comment]
@timelyportfolio Excellent!

**Comment by curran** [comment]
Is there a "tutorials" section anywhere? If so, this would be a good link to add there https://medium.com/@matt_herman/shared-tooltips-in-semiotic-cd8fdf140d5a

**Comment by emeeks** [comment]
Added it to https://github.com/emeeks/semiotic/wiki/Tutorials
