### ISSUE TITLE
Use customPointMark inside scatter plot to show custom image

### ISSUE THREAD

**Issue by bengarvey** [emeeks/semiotic#64]
Trying to do a scatter plot for an upcoming talk. Instead of dots I want to use logos.

The code below works, but has a hard coded javascript logo for all data points. I want to use a different logo for each point.
```
var display = {
	"data": [{
		"x": 0.75,
		"y": 0.75,
		"name": "Semiotic",
		"logo": "img/semiotic.png"
	}, {
		"x": 1,
		"y": 0,
		"name": "Vanilla JS",
		"logo": "img/js.png"
	}, {
		"x": 0.9,
		"y": 0.1,
		"name": "D3",
		"logo": "img/d3.png"
	}, {
		"x": 0.4,
		"y": 0.75,
		"name": "chart.js",
		"logo": "img/chartjs.svg"
	}, {
		"x": 0.3,
		"y": 0.85,
		"name": "Highcharts",
		"logo": "img/highcharts.png"
	}, {
		"x": 0.5,
		"y": 0.5,
		"name": "Plotly",
		"logo": "img/plotly.png"
	}]
};

var sharedProps = { 
  size: [600,600],
  xAccessor: "x",
  yAccessor: "y",
  hoverAnnotation: true,
  margin:{ left: 10, bottom: 30, right: 10, top: 10 }
};

ReactDOM.render(
  <XYFrame
    { ...sharedProps }
    points={display.data}
    customPointMark={ d => (
      <Mark markType="image" width="40px" href="img/js.png"/>
    ) } 
    axes={[
      { orient: 'bottom', ticks: 5, tickFormat: d => d}, 
      { orient: 'left', ticks: 5, tickFormat: d => d}
    ]}  
    margin={{ left: 50, bottom: 30, right: 10, top: 40 }}
  />, 
  document.getElementById('libraries')
);
```

So instead of 
```
    customPointMark={ d => (
      <Mark markType="image" width="40px" href="img/js.png"/>
    ) } 
```
I want to do something like 
```
    customPointMark={ d => (
      <Mark markType="image" width="40px" href={{d.logo}}/>
    ) } 
```

But I can't seem to make it work. I've tried lots of things, but I feel like I'm missing something important.

Progress so far:
![screen shot 2017-10-08 at 4 29 12 pm](https://user-images.githubusercontent.com/1342331/31320633-eabbdbca-ac45-11e7-9317-7ebab5f16e40.png)

**Comment by emeeks** [comment]
Hi Ben,

The data is exposed in a destructured manner. I'll check the docs to make sure they state this properly, but given the forward-compatibility I want to have with the custom element generators, I thought this was for the best, even though it's a hassle to keep track of.

So try this:
`customPointMark={ ({d}) => (
      <Mark markType="image" width="40px" href={{d.logo}}/>
    ) } `

**Comment by bengarvey** [comment]
![screen shot 2017-10-09 at 12 13 26 am](https://user-images.githubusercontent.com/1342331/31325035-b777990c-ac86-11e7-8257-bcfd59d2fd6d.png)

Thanks! Your code was very close and I was able to make it work. Final result:
```
customPointMark={ ({d}) => ( <Mark markType="image" height="40px" href={d.logo}/> ) }
```

**Comment by susielu** [comment]
@bengarvey so cool!

**Comment by bengarvey** [comment]
Follow up to this. My code didn't work in Safari or mobile Chrome, but this does

```
customPointMark={ ({d}) => ( <Mark markType="image" transform="translate(-20,-20)" height="40px" width="40px" type="image/svg+xml" xlinkHref={d.logo}/> ) }
```

**Comment by emeeks** [comment]
@bballcode In OrdinalFrame you can send a `customMark` property as part of the type. So you could use `type={{ type: "swarm", customMark: datapoint => <rect width={5} height={5} fill="red" /> }}` (`datapoint` is your data and drawing instructions, the returned JSX SVG element will be placed at the drawn datapoint). You can use this to draw cool bar charts like this, too:
https://codepen.io/emeeks/pen/aPJbNo
