### ISSUE TITLE
docs/Documentation.js withStyles not yet implemented

### ISSUE THREAD

**Issue by stormasm** [emeeks/semiotic#66]
In Documentation.js 

You import

```
import { withStyles } from "material-ui/styles";
```

And you define a bunch of styles

```
const styles = theme => ({
```

but you are NOT firing it off...

You need one more line of code for it to kick in...

Take a look at this example:

https://github.com/callemall/material-ui/blob/v1-beta/docs/src/pages/demos/drawers/PersistentDrawer.js

Note this line of code:

```
export default withStyles(styles, { withTheme: true })(PersistentDrawer);
```

In order for Documentation.js to activate the styles you defined in **const styles**
you will need to add in the above concept...

Side comment about Semiotic...

I am really impressed with **semiotic**, you have done a super job !

I am closely following how material-ui implements next.js in their docs section,
so I will keep you abreast of the developments and ways for integrating those
ideas into Semiotic.  It might be worth considering using that approach.  But
your custom approach is pretty nice as well...  In fact it might even be better
than the way next.js does it...  Curious to get your feedback and thoughts on
this issue.

Thanks !
-- Michael (stormasm)

**Comment by emeeks** [comment]
Thank you, Michael! Obviously, my documentation has mostly just been copying from others and inserting Semiotic code into it. I'm still trying to work out some of the CSS bugs that showed up with this fix but otherwise it seems better.

Please feel free to make any other docs suggestions (or PRs!). I'm going to close this one.
