### ISSUE TITLE
typo in axis wiki

### ISSUE THREAD

**Issue by eesur** [emeeks/semiotic#69]
[scale: { d3-scale }](https://github.com/emeeks/semiotic/wiki/Axis#scale--d3-scale-) has the same description text as [rotate: { number }](https://github.com/emeeks/semiotic/wiki/Axis#rotate--number-)

semiotic is awesome—super cool you sharing it and appreciate all the hard work with the examples and docs, thank you!

**Comment by emeeks** [comment]
Thank you and thanks for pointing this out, I'll go fix it.
