### ISSUE TITLE
Build unpkg-compatible distribution file?

### ISSUE THREAD

**Issue by tmcw** [emeeks/semiotic#70]
Hello Elijah!

Would there be interest in building a browser-compatible `dist` file so that users could load semiotic from a service like [unpkg](https://unpkg.com/)? This would likely mean running `rollup` on `prepublish` and including the dist file as an entry point under the `unpkg` or `browser` field in package.json ([as mentioned under unpkg's main notes](https://unpkg.com/#/)). If so, happy to take a pass at contributing such a thing.

- Tom

**Comment by emeeks** [comment]
Yes please!!

**Comment by jameswomack** [comment]
@emeeks abacus-build (0 config high perf “easypack” implementation) has a —umd flag to build this too, and it does a lot of bundle size optimizations specific to ES2017 code as well as outputting stats we can use to analyze how core changes are impacting the load performance of Semiotic users. I’ll let you know when I’ve open sourced that so it can be used to produce maximally minified dist files if desired.

**Comment by timelyportfolio** [comment]
This would be great. I built a quick standalone with webpack in my fork but don’t think I get treeshaking.  Also I am just doing manually instead of using package.json

**Comment by susielu** [comment]
I was able to set this up with webpack so that it worked with importing `react-annotation` into CodePen. Here's the setup I used: https://github.com/susielu/react-annotation/blob/master/webpack.config.js 

With this version of `"webpack": "1.13.1"`

And with this script in my package.json `"webpack": "NODE_ENV=production webpack"`

**Comment by curran** [comment]
Would love to be able to use Semiotic on bl.ocks.org!

**Comment by tmcw** [comment]
Going to set aside some time to finally do this today!

**Comment by curran** [comment]
@tmcw I was able to reproduce your fiddle in bl.ocks.org https://bl.ocks.org/curran/8407fbc3d04d5ca06d8045ccaa4cf202/f35b4e70e13e1bd68ef69d42e9d56b282b58194d

The next step would be to get this on UNPKG with UMD build tasks in a `prepublish` step. I created a new issue for this #93

**Comment by timelyportfolio** [comment]
This is fantastic, thanks!
