### ISSUE TITLE
Specify license as SPDX?

### ISSUE THREAD

**Issue by tmcw** [emeeks/semiotic#72]
I noticed that in `package.json`, the license field is [see license in license](https://github.com/emeeks/semiotic/blob/master/package.json#L33) - checking the LICENSE file, it's a standard Apache 2.0 license. Could this instead be `Apache-2.0`, the SPDX identifier for that license, so that npmjs.org will show the license on the package page and projects like fossa are able to efficiently enforce license restrictions?

**Comment by emeeks** [comment]
Pushed an update changing "see license in license" -> "Apache-2.0"

Let me know if there's more I need to do or any other screwups like this.
