### ISSUE TITLE
ReponsiveORFrame question

### ISSUE THREAD

**Issue by jhvanderven** [emeeks/semiotic#73]
I am using Semiotic@1.1.9 in combination with react-grid-layout@0.16.0. Obviously all my ORFrames are ResponsiveORFrames with both ResponseWidth and ResponseHeight set to true. The first type I made was a donut OR Frame and the second a horizontal bar chart. Nothing very special there.

I find that the two frames exhibit very different behaviour.

The donut seems to require the size property in order to grow beyond its initial size. If I give it maximum size on creation, then let react-grid-layout set the actual initial size all works as expected. If I do not give it a size, I think the default in semiotic [500, 500] will be the maximum size.

Because a donut is a circle, I kind of understand that it only responds to width changes...

The bar chart works the same with or without an initial size: it only resizes in the width direction. It will not change the height (because it's vertical) of its pieces to fit the allotted space. The width of the bar chart does grow beyond 500.

Here is the bar chart:

```
        <ResponsiveORFrame
          responsiveWidth={true}
          responsiveHeight={true}
          //size={[this.props.size[0], this.props.size[1]]} 
          data={this.state.data}
          projection={"horizontal"}
          type={"bar"}
          oLabel={true}
          oPadding={this.props.padding}
          oAccessor={"key"}
          rAccessor={d => d.count}
          style={d => {
            return { fill: this.props.fill, stroke: "black" };
          }}
        />

```

And here is the donut

```
          <ResponsiveORFrame
            responsiveWidth={true}
            responsiveHeight={true}
            size={[this.props.size[0], this.props.size[1]]}
            data={this.state.data}
            projection={"radial"}
            style={(d, i) => ({
              fill: this.props.colors[i],
              strokeWidth: 1
            })}
            type={{ type: "bar", innerRadius: this.innerRadius() }}
            dynamicColumnWidth={"count"}
            rAccessor={d => 1}
            oAccessor={"key"}
            margin={{ left: 20, top: 40, bottom: 40, right: 20 }}
          />
```

The frames have a default size on which they render nicely. That is what the addFrame function uses:
```
  addFrame(e){
    let size = this.getDefaultSize(frameType);
    this.setState({
      layout:this.state.layout.concat({
        i:this.state.count.toString(),
        x:4,
        y:Infinity,
        w:Math.ceil(size[0] * gridCols / gridWidth),
        h:Math.ceil(size[1]/gridHeight)
      }),
      frames: this.state.frames.concat({
        key:this.state.count.toString(),
        data:{
          type:frameType
        }
      }),
      count:this.state.count+1,
    });
  }

```

The above is the bookkeeping and initial sizing of the frames on the page. The actual creation is done here (adapted from the react-grid-layout example [here](https://strml.github.io/react-grid-layout/examples/6-dynamic-add-remove.html)):

```
  createElement(el){
    const i = el.add ? '+' : el.i;
    var item;
    var type = '';
    for (var frame of this.state.frames) {
      if(frame.key===el.i){
        type = frame.data.type;
        break;
      }
    }
    switch(type){
      case 'donut':
        // largest size of a rectangular frame here.
        item= <donut 
                size={[gridWidth, gridWidth]} 
              />
        break;
      case 'barchart':
        item=<barchart />
        break;
      default:
        console.error('Unknown frame');
    }
    return (
      <div id={type+i} key={i} data-grid={el}>
        {item}
      </div>
    );
  }

```

Two questions:
1) Do I need to set a size on responsive semiotic frames? Can they then grow to any size?
2) What should I do to make the frames respond in height?

**Comment by emeeks** [comment]
1. No, you shouldn't have to, it would be a bug if it's behaving that way.
2. They should respond to changes in height, though make sure that their parents in CSS are actually getting height data passed down to them, as CSS height doesn't always come along like CSS width does, so ensure that the parent nodes have height.

I'm going to assume they do and assume #2 is also a bug and start to dig into it. If there's a way you could send me a minimal working example (either using something like stackblitz or a repo) then that would help.

**Comment by jhvanderven** [comment]
Ok. I created a blitz: [donut-barchart](https://react-phqwom.stackblitz.io) feel free to edit it: [edit](https://stackblitz.com/edit/react-phqwom)

**Comment by emeeks** [comment]
I took a look at the example you posted and it rendered the donut chart fine when I set `size` to `undefined`. I assume this has something to do with the CSS in your actual app versus CSS being sent down by StackBlitz. I'll try to find some time to clone the code itself and see if I can come up with some documentation that helps to explain the CSS gotchas involved.

**Comment by jhvanderven** [comment]
On the blitz the behaviour is the same as in my 'real' app. It stops growing after a certain size, and then only the hole in the donut grows. I should perhaps have made 2 issues out of this one, as I also don't understand why the bar chart (but probably the donut as well) do not react to height changes.

**Comment by emeeks** [comment]
Oh I didn't realize, I'll look more closely at it.

**Comment by emeeks** [comment]
I found the problem, it seems I need to hardwire my own responsive container div to have height:100% in order for it to properly listen for height changes. I'll have a fix in an updated version tomorrow.

**Comment by emeeks** [comment]
I don't see anything with the donut hole growing, though maybe that was an artifact of the height being ignored. I'll keep testing it out, though. It may be your inner radius function? I haven't tried to look through its logic yet.

**Comment by emeeks** [comment]
@jhvanderven The height resizing should be fixed in 1.1.10 could you test it with your code and see if you still have any problems?

**Comment by jhvanderven** [comment]
I updated the blitz to 1.1.13. The behaviour still looks the same. Maybe I am expecting something that just is not there: if you use the hamburger to create a bar chart, I expect it to adjust its size to fit the griditem, but it does not.
![image](https://user-images.githubusercontent.com/2427214/32535101-f028dd6c-c458-11e7-8ce3-baf86624243b.png)

**Comment by emeeks** [comment]
That's the proper expectation. I'll take a look and see what I missed.

**Comment by emeeks** [comment]
This seems to work if you set the `<div>` wrapping your `ORFrame` to have `height: 100%` and `width: 100%`:

https://stackblitz.com/edit/react-egxkrq?file=BarChart.js

**Comment by jhvanderven** [comment]
Great! That works. Thanks

**Comment by EmSyndio** [comment]
this ResponsiveORFrame has a very weird way to be responsive; it doesn't play well with my flex box containers.

The easy way to make SVG responsive is to set:
```
<svg width="100%" height="100%" viewBox={`0 0 ${width} ${height}`}  preserveAspectRatio="xMinYMin meet"></svg>
```

That will scale to any container gracefully, without re-rendering, and rendering the graph at the size defined by viewBox.
That also allows to re-scale the labels, title etc... to look nicer by adjusting the viewBox settings and re-render in a larger box: keeping font size the same, the graph elements scale but not the text, making for better looking charts in full screen.

How can I affect the `svg` attributes through the API?

**Comment by EmSyndio** [comment]
similarly, how could I affect the 'responsive-container'. want to set the height of my chart and have the container expand. If i set the height, with height=100%, the chart overflows over the container boundary: it needs to have height=auto to expand properly.

**Comment by emeeks** [comment]
That's a good point. I don't often think about `viewBox` because it's not part of my practice but it should be available for users to work with if they want straightforward graphical zoom. I'll get to work on building out support for that.

**Comment by Sivli-Embir** [comment]
@emeeks sorry to bump such an old issue but I can't seem to find where this got resolved. Was this dropped or did it not get mentioned in the docs? Thanks.
