### ISSUE TITLE
ORFrame Annotation Marginalia settings broken

### ISSUE THREAD

**Issue by susielu** [emeeks/semiotic#90]
When I try to use ORFrame with AnnotationSettings with layout = "marginalia" it breaks on the following error: 

![screen shot 2017-11-14 at 3 00 58 pm](https://user-images.githubusercontent.com/1449837/32809802-2b43835e-c94d-11e7-8a36-797092363427.png)

**Comment by emeeks** [comment]
This will be fixed in the next version
