### ISSUE TITLE
pie chart/responsive question

### ISSUE THREAD

**Issue by j0shuachen** [emeeks/semiotic#91]
Hi, I came across semiotic while reading a medium article and really liked the sketchy effect that can be used to create the charts. I've ran into some issues that I'm hoping I can get some help on.

In my data set, there are certain cases where one category makes up 100% of the data and the other category makes up 0%. When the data is passed in, the chart still draws a slice for the category that is 0%. I've also tried using conditionals to set up the data passed in. For example, if the female category data is 0, then disregard that category and only pass in the male category data which should fill up 100% of the chart for sure. This still results in an incorrect pie chart though. I've attached a screen shot below.

Another question I have is how to make the charts responsive. I noticed that the example charts don't seem to be responsive so I'm wondering if you can create a tutorial or example. Right now I've resorted to removing the viewport tag which is probably not ideal.

Thanks for any help in advance.

![screen shot 2017-11-16 at 8 53 29 am](https://user-images.githubusercontent.com/28281411/32905375-9dad472e-caae-11e7-8143-91385dde1689.png)
![screen shot 2017-11-16 at 9 02 56 am](https://user-images.githubusercontent.com/28281411/32905378-9e6859f6-caae-11e7-9ca0-c51e1104b827.png)

**Comment by emeeks** [comment]
I'll take a look at the pie with 0 data issue.

There are Responsive charts, each frame has a responsive version, like ResponsiveXYFrame. However, I'm not using responsive charts in the documents. I'll take a look at having a few responsive examples in the docs.

**Comment by emeeks** [comment]
Okay so looking into this my guess is that you have `oPadding` set that's being honored for the single value in the pie chart. When I have `oPadding` set to 0, I don't see any problem but when I have it set higher than that, I see the behavior you have. I'm going to update the code to better handle this situation but if you change `oPadding` to 0 then you should see good results

**Comment by j0shuachen** [comment]
Thanks! Changing the oPadding to 0 did fix it. Is there another way to have the pie chart slices display like the image below without oPadding though?

I'm still having issues with the responsive version of the charts as well, but I'll try playing around with it some more.

![screen shot 2017-11-20 at 12 08 51 pm](https://user-images.githubusercontent.com/28281411/33039095-b948f1d2-cdeb-11e7-8ab4-e30147851bf8.png)

**Comment by emeeks** [comment]
No, there isn't but the next version should include a fix so that oPadding isn't honored for a pie with only one value.

**Comment by emeeks** [comment]
Fixed in 1.2.5
