### ISSUE TITLE
Host distribution files on UNPKG

### ISSUE THREAD

**Issue by curran** [emeeks/semiotic#93]
As a follow-on to https://github.com/emeeks/semiotic/issues/70 and https://github.com/emeeks/semiotic/pull/92 , the built files need to go into NPM to get exposed via UNPKG.

This can be done by putting build tasks in a `prepublish` step, much the same way as the D3 modules do it, for example https://github.com/d3/d3-selection/blob/master/package.json#L28

**Comment by emeeks** [comment]
@curran I've pinged folks on various channels but this doesn't seem to produce a working unkpg endpoint. I removed graphology as a result (something I've been thinking of doing) and it was complaining but even with that I get issues with `babelHelpers is not defined` as in this example:
https://codepen.io/emeeks/pen/KyovjB

**Comment by timelyportfolio** [comment]
Now is it possible to uglify #92.  I wish I knew more about package.json, and I would submit a pull.

**Comment by emeeks** [comment]
Rollup is creating `/dist/semiotic.js` it's just giving an error when referenced in that pen. While I could just add an uglify/webpack build step to create a static file and use Rawgit, I'd rather use the rollup/unpkg approach.

**Comment by emeeks** [comment]
@tmcw updated the rollup version and settings and look at https://codepen.io/emeeks/pen/KyovjB now.
<img width="1262" alt="screen shot 2017-11-21 at 9 14 05 pm" src="https://user-images.githubusercontent.com/495634/33111109-f63b6f8c-cf00-11e7-979f-b1a25852024f.png">

**Comment by emeeks** [comment]
Here's a pen working with unpkg:
https://codepen.io/emeeks/pen/jazQJr

Though I still have to give a relative path to /dist/ so I assume some setting is still off but that can be resolved later. This is so cool.

**Comment by curran** [comment]
My guess is babel-standalone may have been omitted. I find it a bit hard to tell what's going in on Codepen regarding external script inclusion.

Here's a working example on bl.ocks.org bl.ocks.org/curran/8407fbc3d04d5ca06d8045ccaa4cf202

Woooooo :tada: 

Regarding the `/dist` in the path, I think it's pretty standard actually to have it there in the codepen URL. I've also seen variants like `/umd` or `/lib`.

I can see windows of possibility opening up!

Next thing is to include a minified build on UNPKG - this dist file is fairly large at 1.2MB

**Comment by curran** [comment]
Created a new issue "Host minified dist file on UNPKG" #96
