### ISSUE TITLE
Host minified dist file on UNPKG

### ISSUE THREAD

**Issue by curran** [emeeks/semiotic#96]
As a follow-on to https://github.com/emeeks/semiotic/issues/93#issuecomment-346201111 and https://github.com/emeeks/semiotic/pull/92 , the final task for a prim and proper UNPKG distribution is to include a minified version. The unminified dist file is fairly large at 1.2MB.

We may even want to consider _only_ including the minified version, as presently anyone who `npm install`s Semiotic will have to eat an extra 1.2MB download.

When this id done, a minified file should appear in this list here: [https://unpkg.com/semiotic@1.2.7/dist/](https://unpkg.com/semiotic@1.2.7/dist/)

**Comment by jimaek** [comment]
jsDelivr can auto-minify the files for you. You can use that as an alternative 

https://cdn.jsdelivr.net/npm/semiotic@1.2.7/dist/semiotic.min.js
https://cdn.jsdelivr.net/npm/semiotic

**Comment by timelyportfolio** [comment]
Can we get a version bump, so that minified files will show up?  I know I am being greedy, but I'd love to move away from my temporary standalone build.  Thanks everyone!

**Comment by curran** [comment]
@timelyportfolio Agreed

**Comment by emeeks** [comment]
1.2.9 published and `semiotic.min.js` seems to be working in my Codepen.
