### ISSUE TITLE
Open to using Unleash for releases instead of the shell scripts?

### ISSUE THREAD

**Issue by jameswomack** [emeeks/semiotic#98]
### Issues w/ the current setup

1. [shell-based scripts](https://github.com/emeeks/semiotic/blob/master/package.json#L12:14)
  * They don't work on Windows by default, limits the places from which releases can be made and who can make them
  * Shell scripting introduces a new language to use
  * Shell scripts are harder to debug
  * Shell scripts make it harder to re-use code, rely on vendor innovations etc.
2. Scripts are committed to this repo instead of having used an existing solution
  * Must be maintained by you
  * Won't leverage improvements made by others
3. The release process is spread over several scripts despite some needing to be run together
  * Makes it unclear what should be run and when
  * Some duplication across the scripts
4. The script code itself doesn't have error recovery, detailed messages etc.

### Solution

Use [Unleash](https://github.com/Netflix/unleash). It's been used to publish thousands of packages, contains all the features you're currently using (and more) and doesn't need to be maintained by you.

**Comment by emeeks** [comment]
Gonna close this. I'm open to changing the way scripts are managed but it's not something I'm terribly familiar with but I am open to PRs on the subject.
